// napcs_config.js — National Configuration & Summary Data
// PLT Strategies Group, Inc. | NAPCS Unionization Research Project
// Auto-generated by NAPCS_Dashboard_School_Builder_v2.js
// Data Currency Date: June 16, 2026
// National denominator: 7,888 open schools (PDR-020)
// Schema: napcsStatus / napcsSubStatus — census methodology framing
// DO NOT EDIT MANUALLY — rebuild from source files

var NAPCS_CONFIG = {
  "national": {
    "universe": 7888,
    "confirmed": 363,
    "dependent": 520,
    "combined": 883,
    "density": "11.2%",
    "confirmed_density": "4.6%",
    "dependent_density": "6.6%",
    "organizing": 18,
    "decertified": 11,
    "closed": 26,
    "jurisdictions": 33,
    "dataDate": "June 16, 2026",
    "denominatorNote": "Registry-verified open schools only (PDR-020, locked June 11, 2026)"
  },
  "state_data": {
    "AK": {
      "name": "Alaska",
      "universe": 32,
      "conf": 0,
      "dep": 32,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "100.0%",
      "lb": "ALRA (AK)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Alaska has no right-to-work statute. AS 23.40 (PERA) and AS 14.03.270 govern public employee labor relations without RTW restriction.",
        "effectiveDate": "N/A",
        "notes": "Alaska is not a right-to-work state. Charter school teachers covered by district CBAs under AS 14.03.270(b) are subject to the full terms of the district NEA-Alaska CBA, which may include union security provisions."
      },
      "note": "",
      "deferred": false
    },
    "AL": {
      "name": "Alabama",
      "universe": 23,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R10",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Ala. Code §25-7-30 through §25-7-36",
        "effectiveDate": "1953",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "AR": {
      "name": "Arkansas",
      "universe": 109,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "National Labor Relations Board — Region 15 (New Orleans)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Arkansas Constitution Amendment 34 (1944); Ark. Code Ann. §11-3-303 et seq.",
        "effectiveDate": "1944-01-01",
        "notes": "Arkansas was the first state to adopt right-to-work via constitutional amendment (1944) — the longest-standing RTW state in the NAPCS dataset. Employees at any organized AR charter school cannot be required to join a union or pay dues as a condition of employment."
      },
      "note": "",
      "deferred": false
    },
    "AZ": {
      "name": "Arizona",
      "universe": 562,
      "conf": 4,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.7%",
      "lb": "NLRB Region 28 (Phoenix)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "A.R.S. §23-1302",
        "effectiveDate": "1947",
        "notes": "Right-to-work state. Applies to private-sector workers under NLRA."
      },
      "note": "",
      "deferred": false
    },
    "CA": {
      "name": "California",
      "universe": 1246,
      "conf": 189,
      "dep": 113,
      "org": 2,
      "dec": 4,
      "clo": 9,
      "watch": 2,
      "density": "24.2%",
      "lb": "PERB(CA) — California Public Employment Relations Board",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Gov. Code §3540 et seq. (EERA)",
        "effectiveDate": "",
        "notes": "Not a right-to-work state. EERA governs public-sector charter employers."
      },
      "note": "",
      "deferred": false
    },
    "CO": {
      "name": "Colorado",
      "universe": 260,
      "conf": 0,
      "dep": 0,
      "org": 9,
      "dec": 0,
      "clo": 0,
      "watch": 9,
      "density": "0.0%",
      "lb": "NLRB R27",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Colorado has no right-to-work statute. The Colorado Labor Peace Act (CRS §§ 8-3-101 et seq.) governs private-sector labor relations but does not include right-to-work provisions. Union security provisions are available in collective bargaining agreements for private-sector employers.",
        "effectiveDate": "N/A",
        "notes": "CO charter schools are private employers under the NLRA. Union security clauses are permissible."
      },
      "note": "",
      "deferred": false
    },
    "CT": {
      "name": "Connecticut",
      "universe": 21,
      "conf": 4,
      "dep": 1,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "23.8%",
      "lb": "SBLR (CT)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Connecticut has no right-to-work statute. Conn. Gen. Stat. §31-101 et seq. (Connecticut Labor Relations Act) and TNA (§10-153a et seq.) permit union security provisions.",
        "effectiveDate": "N/A",
        "notes": "Agency fee and union security clauses are available in both TNA and NLRB-governed CBAs in Connecticut."
      },
      "note": "",
      "deferred": false
    },
    "DC": {
      "name": "Washington, D.C.",
      "universe": 125,
      "conf": 7,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "5.6%",
      "lb": "NLRB",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Washington DC is not a right-to-work jurisdiction. DC charter schools are private employers under the NLRA; no DC right-to-work statute exists and the NLRA preempts any such provision.",
        "effectiveDate": "N/A",
        "notes": "Union security provisions are available in CBA negotiations for DC charter school unions."
      },
      "note": "",
      "deferred": false
    },
    "DE": {
      "name": "Delaware",
      "universe": 23,
      "conf": 4,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "17.4%",
      "lb": "PERB(DE)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Delaware has no right-to-work statute. DE charter school employees are public employees under 14 Del.C. Chapter 40; PERB(DE) has jurisdiction. Union security provisions are standard in public-sector CBAs.",
        "effectiveDate": "N/A",
        "notes": "No right-to-work statute applies. All DE charter schools are public employers — NLRA and any RTW provisions are inapplicable."
      },
      "note": "",
      "deferred": false
    },
    "FL": {
      "name": "Florida",
      "universe": 730,
      "conf": 5,
      "dep": 3,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "1.1%",
      "lb": "PERC (FL)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Art. X §12, Florida Constitution",
        "effectiveDate": null,
        "notes": "Florida is a right-to-work state by constitutional provision. Union security clauses (mandatory dues/fees) are not available for FL charter school unions. SB256 (2023) added annual recertification requirements for public-sector unions falling below 60% dues-paying membership. Right-to-work applies to PERC(FL)-jurisdiction charter schools as public employers and to any NLRB-jurisdiction charter schools as private employers."
      },
      "note": "",
      "deferred": false
    },
    "GA": {
      "name": "Georgia",
      "universe": 94,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R10 (Atlanta)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Georgia Code §34-6-6 — right-to-work statute enacted 1947. Union security agreements (union shop, agency fee) are not available for any employer-employee relationship in Georgia, including NLRB-jurisdiction charter schools.",
        "effectiveDate": "1947",
        "notes": "Right-to-work status means that even if a GA charter school were certified, union security clauses would be unavailable in CBA negotiations."
      },
      "note": "",
      "deferred": false
    },
    "HI": {
      "name": "Hawaii",
      "universe": 37,
      "conf": 0,
      "dep": 37,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "100.0%",
      "lb": "HLRB (HI)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "HRS Art. XIII §2; HRS Ch. 89",
        "effectiveDate": "",
        "notes": "Not a right-to-work state. Strong public-sector bargaining rights under HRS Chapter 89."
      },
      "note": "",
      "deferred": false
    },
    "IA": {
      "name": "Iowa",
      "universe": 10,
      "conf": 0,
      "dep": 3,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "30.0%",
      "lb": "Dual jurisdiction: NLRB R33 (Track A) / Iowa PERA Iowa Code §20 (Track B)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Iowa Code Ch. 731 (Iowa Right to Work Act)",
        "effectiveDate": "1947-01-01",
        "notes": "Iowa has been right-to-work since 1947. Applies to Track A schools. Track B schools are public employers under Iowa PERA — RTW does not apply in the same way but Iowa PERA was significantly restricted in 2017 (mandatory subjects of bargaining limited to base wages only)."
      },
      "note": "",
      "deferred": false
    },
    "ID": {
      "name": "Idaho",
      "universe": 84,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R19",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Idaho Code §44-2101 through §44-2104",
        "effectiveDate": "1985",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "IL": {
      "name": "Illinois",
      "universe": 132,
      "conf": 30,
      "dep": 1,
      "org": 0,
      "dec": 0,
      "clo": 6,
      "watch": 0,
      "density": "23.5%",
      "lb": "NLRB (Region 13) / IELRB",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Illinois has no right-to-work statute.",
        "effectiveDate": null,
        "notes": "Applies to both NLRB (private-sector charters) and IELRB (public-employer charters). Union security agreements are permissible in both jurisdictions."
      },
      "note": "",
      "deferred": false
    },
    "IN": {
      "name": "Indiana",
      "universe": 132,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "IEERB/NLRB R25",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Ind. Code §22-6-6",
        "effectiveDate": "2012",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "KS": {
      "name": "Kansas",
      "universe": 8,
      "conf": 0,
      "dep": 8,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "100.0%",
      "lb": "Kansas Department of Labor — Labor Relations Division (PNA/PERB)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "K.S.A. 44-831 (Kansas Labor-Management Relations Act, Article 8)",
        "effectiveDate": "1958-01-01",
        "notes": "Kansas has been right-to-work since 1958. Applies to any NLRB private employer organizing — though KS charter schools are public employers under the PNA (K.S.A. 72-2218 et seq.), RTW principles do not apply in the same way to PNA-covered employees. Under PNA, no employee can be required to join a professional association."
      },
      "note": "",
      "deferred": false
    },
    "LA": {
      "name": "Louisiana",
      "universe": 139,
      "conf": 4,
      "dep": 0,
      "org": 0,
      "dec": 1,
      "clo": 1,
      "watch": 0,
      "density": "2.9%",
      "lb": "LSCSC / NLRB R15",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "La. R.S. §23:982",
        "effectiveDate": null,
        "notes": "Louisiana is a right-to-work state. Union security clauses are not available for LA charter school unions. Applies to Type 1/3/3B OPSB-authorized schools under NLRB jurisdiction as private employers. Type 2/5 schools under Act 172 LSCSC routing have no established collective bargaining procedure as of June 2026."
      },
      "note": "",
      "deferred": false
    },
    "MA": {
      "name": "Massachusetts",
      "universe": 73,
      "conf": 8,
      "dep": 5,
      "org": 0,
      "dec": 1,
      "clo": 1,
      "watch": 0,
      "density": "17.8%",
      "lb": "DLR (MA)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Massachusetts has no right-to-work statute. MA charter school employees are classified as public employees under M.G.L. c. 71 §89(y) and bargain under M.G.L. c. 150E. Agency fee provisions are available in collective bargaining agreements.",
        "effectiveDate": "N/A",
        "notes": "No right-to-work statute applies to any MA charter school employer or employee."
      },
      "note": "",
      "deferred": false
    },
    "MD": {
      "name": "Maryland",
      "universe": 52,
      "conf": 0,
      "dep": 51,
      "org": 0,
      "dec": 0,
      "clo": 2,
      "watch": 0,
      "density": "98.1%",
      "lb": "PERB (MD)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Md. Ed. Article §9-108; Md. Labor & Employment",
        "effectiveDate": "",
        "notes": "Not a right-to-work state. All charter schools BLANKET_DEPENDENT under §9-108."
      },
      "note": "",
      "deferred": false
    },
    "ME": {
      "name": "Maine",
      "universe": 11,
      "conf": 1,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "9.1%",
      "lb": "NLRB",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Maine has no right-to-work statute. Maine is a private-sector state under NLRA jurisdiction for charter schools; union security provisions are available in CBA negotiations.",
        "effectiveDate": "N/A",
        "notes": "No right-to-work statute applies to ME charter schools."
      },
      "note": "",
      "deferred": false
    },
    "MI": {
      "name": "Michigan",
      "universe": 373,
      "conf": 10,
      "dep": 0,
      "org": 1,
      "dec": 0,
      "clo": 0,
      "watch": 1,
      "density": "2.7%",
      "lb": "MERC / NLRB Region 7",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Mich. Comp. Laws §423.14 (enacted 2012, effective 2013; repealed February 2024 for private-sector NLRB-jurisdiction employers)",
        "effectiveDate": "2013 (enacted); repealed February 2024 for NLRB-jurisdiction",
        "notes": "Michigan enacted right-to-work in 2012 (effective March 2013). Michigan voters passed Proposition 22 in November 2022 repealing right-to-work for private-sector workers; repeal took effect February 2024. NLRB-jurisdiction charter schools (privately incorporated) are now no longer subject to right-to-work — new CBAs may include union security clauses. MERC-jurisdiction charter schools (public employers) were never subject to right-to-work; PERA governs. RTW status: effectively NO for NLRB-jurisdiction charters as of February 2024; never applied to MERC-jurisdiction charters."
      },
      "note": "",
      "deferred": false
    },
    "MN": {
      "name": "Minnesota",
      "universe": 309,
      "conf": 8,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "2.6%",
      "lb": "BMS (MN)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Minnesota has no right-to-work statute. Right-to-work legislation has been proposed in the Minnesota Legislature but has not been enacted. MN charter school employees are public employees under PELRA (Minn. Stat. §179A) following the 2023 amendments; union security provisions are available in collective bargaining agreements.",
        "effectiveDate": "N/A",
        "notes": "RTW legislation proposed but not enacted as of May 2026."
      },
      "note": "",
      "deferred": false
    },
    "MO": {
      "name": "Missouri",
      "universe": 81,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 1,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R14 (St. Louis) + NLRB R17 (Kansas City)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Missouri right-to-work law (RSMo §290.590, enacted 2017) was rejected by voter referendum August 7, 2018 (67% opposed). Missouri has no operative right-to-work statute. Union security provisions are available in collective bargaining agreements.",
        "effectiveDate": "N/A — RTW law repealed by referendum August 2018",
        "notes": "Missouri voters rejected right-to-work 67-33% in August 2018. The 2017 statute never took effect. Union security clauses are available in MO charter school CBAs under NLRA."
      },
      "note": "",
      "deferred": false
    },
    "MS": {
      "name": "Mississippi",
      "universe": 10,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R15",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Miss. Code Ann. §71-1-47",
        "effectiveDate": "1954",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "NC": {
      "name": "North Carolina",
      "universe": 213,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R11",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "N.C. Gen. Stat. §95-78 through §95-84",
        "effectiveDate": "1947",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "NH": {
      "name": "New Hampshire",
      "universe": 33,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "PELRB (NH)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "New Hampshire has no right-to-work statute. RSA 273-A and RSA 194-B govern NH public employee labor relations without RTW restriction.",
        "effectiveDate": "N/A",
        "notes": "NH charter school teachers are public employees under PELRB. Union security provisions are permissible under NH public employee law. NH is not a right-to-work state."
      },
      "note": "",
      "deferred": false
    },
    "NJ": {
      "name": "New Jersey",
      "universe": 86,
      "conf": 19,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "22.1%",
      "lb": "PERC (NJ)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "New Jersey has no right-to-work statute.",
        "effectiveDate": null,
        "notes": "NJ charter school employees are public employees under PERC(NJ) jurisdiction (EERA). Right-to-work statutes apply only to private-sector NLRA employers. Not applicable to NJ charter schools."
      },
      "note": "",
      "deferred": false
    },
    "NM": {
      "name": "New Mexico",
      "universe": 98,
      "conf": 3,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "3.1%",
      "lb": "PELRB (confirmed for J Paul Taylor Academy) / CONTESTED PELRB or NLRB Region 28 (other schools)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "N.M. Stat. Ann. §50-11-1 et seq.",
        "effectiveDate": "",
        "notes": "Not a right-to-work state. Jurisdictional ambiguity between PELRB and NLRB R28 for charter schools."
      },
      "note": "",
      "deferred": false
    },
    "NV": {
      "name": "Nevada",
      "universe": 104,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "EMRB(NV)/NLRB R28",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "",
        "effectiveDate": "",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "NY": {
      "name": "New York",
      "universe": 350,
      "conf": 24,
      "dep": 4,
      "org": 0,
      "dec": 2,
      "clo": 0,
      "watch": 0,
      "density": "8.0%",
      "lb": "PERB(NY)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "New York has no right-to-work statute.",
        "effectiveDate": null,
        "notes": "NY charter school employees are statutory public employees under Education Law Article 56 (Taylor Law jurisdiction). Right-to-work statutes apply only to private-sector NLRA employers. PERB(NY)-jurisdiction schools are public employers and not subject to right-to-work. NLRB-jurisdiction independently incorporated NY charters are private employers — no right-to-work statute applies in New York."
      },
      "note": "",
      "deferred": false
    },
    "OH": {
      "name": "Ohio",
      "universe": 323,
      "conf": 13,
      "dep": 14,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "8.4%",
      "lb": "NLRB (Region 8 / Region 9)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Ohio has no right-to-work statute for private-sector employees. NLRA preempts state right-to-work law for private employers, and Ohio has enacted no such statute. Ohio public employees retain full collective bargaining rights under ORC Chapter 4117 (SB 5, enacted 2011, was repealed by voter referendum November 2011).",
        "effectiveDate": "N/A",
        "notes": "No right-to-work statute applies to Ohio charter schools, which are private employers under the NLRA. Union security provisions (agency fee, union shop) are available in CBA negotiations."
      },
      "note": "",
      "deferred": false
    },
    "OK": {
      "name": "Oklahoma",
      "universe": 73,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R17",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Okla. Stat. tit. 40, §§481-490",
        "effectiveDate": "2001",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "OR": {
      "name": "Oregon",
      "universe": 128,
      "conf": 2,
      "dep": 120,
      "org": 0,
      "dec": 2,
      "clo": 0,
      "watch": 0,
      "density": "95.3%",
      "lb": "ERB (OR)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Oregon has no right-to-work statute.",
        "effectiveDate": null,
        "notes": "Oregon is a non-right-to-work state. ORS Chapter 243 (PECBA) governs public employer charter schools (ERB jurisdiction). Union security clauses are permissible. Independently incorporated OR charter schools that are private employers under NLRA (NLRB jurisdiction) are also not subject to right-to-work — no Oregon right-to-work statute exists for either jurisdiction."
      },
      "note": "",
      "deferred": false
    },
    "PA": {
      "name": "Pennsylvania",
      "universe": 175,
      "conf": 23,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 2,
      "watch": 0,
      "density": "13.1%",
      "lb": "NLRB",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Pennsylvania has no right-to-work statute. Right-to-work legislation has been introduced in the Pennsylvania General Assembly but has not been enacted. PA charter school employees are private-sector employees under the NLRA; union security provisions are available in collective bargaining agreements.",
        "effectiveDate": "N/A",
        "notes": "RTW legislation has been proposed but not enacted as of May 2026."
      },
      "note": "",
      "deferred": false
    },
    "RI": {
      "name": "Rhode Island",
      "universe": 42,
      "conf": 4,
      "dep": 2,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "14.3%",
      "lb": "NLRB Region 1 (Boston)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Rhode Island has no right-to-work statute. RI charter school employees are private-sector employees under the NLRA; union security provisions are available in CBA negotiations.",
        "effectiveDate": "N/A",
        "notes": "The unresolved question in RI is whether the state teacher strike prohibition (applicable to public-sector educators under RIPLRA) applies to NLRB-organized charter school employees. Federal court proceedings pending as of May 2026."
      },
      "note": "",
      "deferred": false
    },
    "SC": {
      "name": "South Carolina",
      "universe": 104,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R11",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "S.C. Code Ann. §41-7-10 through §41-7-90",
        "effectiveDate": "1954",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "TN": {
      "name": "Tennessee",
      "universe": 112,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R10",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Tenn. Code Ann. §50-1-201",
        "effectiveDate": "1947",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "TX": {
      "name": "Texas",
      "universe": 1056,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R16",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Tex. Lab. Code §101.052 through §101.053",
        "effectiveDate": "1993",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "UT": {
      "name": "Utah",
      "universe": 141,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R28",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Utah Code Ann. §34-34-1 through §34-34-17",
        "effectiveDate": "1955",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "VA": {
      "name": "Virginia",
      "universe": 7,
      "conf": 0,
      "dep": 2,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "28.6%",
      "lb": "Dual jurisdiction: Va. Code §40.1-57.2 (district CB law, 2 schools) / NLRB R5 Baltimore (5 schools)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Virginia Code §40.1-58 et seq. (Virginia Right to Work Act)",
        "effectiveDate": "1947-01-01",
        "notes": "Virginia has been right-to-work since 1947. Employees at any organized VA charter school cannot be required to join a union or pay dues as a condition of employment. Applies to both NLRB private employer schools and schools covered by the Va. Code §40.1-57.2 state CB framework."
      },
      "note": "",
      "deferred": false
    },
    "WA": {
      "name": "Washington",
      "universe": 15,
      "conf": 1,
      "dep": 0,
      "org": 6,
      "dec": 0,
      "clo": 0,
      "watch": 6,
      "density": "6.7%",
      "lb": "PERC (WA)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Washington has no right-to-work statute. RCW 41.56.0251 classifies WA charter school employees as public employees under PECBA — union security provisions are standard in WA public employee collective bargaining agreements.",
        "effectiveDate": "N/A",
        "notes": "WA charter school employees are public employees under RCW 41.56.0251 (SB 6194, 2016). PERC (Public Employment Relations Commission) has exclusive jurisdiction. Public employee union security is standard in WA."
      },
      "note": "",
      "deferred": false
    },
    "WI": {
      "name": "Wisconsin",
      "universe": 237,
      "conf": 0,
      "dep": 124,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "52.3%",
      "lb": "WERC (WI) / NLRB R18",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Wisconsin right-to-work (Wis. Stat. §111.04) applies to private-sector NLRA employers only. Does not apply to WERC-jurisdiction public employers.",
        "effectiveDate": "2015",
        "notes": "WI enacted right-to-work for private-sector employees in 2015 (Wis. Stat. §111.04). All 124 DEPENDENT WI charter schools are LEA instrumentalities — public employers under WERC jurisdiction (MERA). Right-to-work does not apply to WERC-jurisdiction schools. NLRB R18 non-instrumentality charters are private employers and are subject to right-to-work; union security clauses are not available."
      },
      "note": "",
      "deferred": false
    },
    "WV": {
      "name": "West Virginia",
      "universe": 8,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R9",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "WV Code §21-1A-1 et seq. (West Virginia Workplace Freedom Act, effective July 1, 2016)",
        "effectiveDate": "2016-07-01",
        "notes": "WV right-to-work applies to all collective bargaining contracts entered into, modified, renewed, or extended after July 1, 2016. Employees cannot be required to join a union or pay dues as a condition of employment. Separately, WV Code §18-5-45a declares that public school district employees have no right to collective bargaining — but this applies to district employees, not charter school employees who organize under NLRB private employer framework."
      },
      "note": "",
      "deferred": false
    },
    "WY": {
      "name": "Wyoming",
      "universe": 8,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R27",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Wyo. Stat. Ann. §27-7-109",
        "effectiveDate": "1963",
        "notes": ""
      },
      "note": "",
      "deferred": true
    }
  },
  "state_centers": {
    "AK": [
      64.2,
      -153
    ],
    "AL": [
      32.8,
      -86.8
    ],
    "AR": [
      34.8,
      -92.2
    ],
    "AZ": [
      34.3,
      -111.1
    ],
    "CA": [
      37.2,
      -119.4
    ],
    "CO": [
      39,
      -105.5
    ],
    "CT": [
      41.6,
      -72.7
    ],
    "DC": [
      38.9,
      -77
    ],
    "DE": [
      39,
      -75.5
    ],
    "FL": [
      28,
      -82.5
    ],
    "GA": [
      32.7,
      -83.5
    ],
    "HI": [
      20.9,
      -157
    ],
    "IA": [
      42,
      -93.5
    ],
    "ID": [
      44,
      -114.5
    ],
    "IL": [
      40,
      -89.2
    ],
    "IN": [
      40,
      -86.1
    ],
    "KS": [
      38.5,
      -98
    ],
    "LA": [
      31,
      -91.8
    ],
    "MA": [
      42.3,
      -71.8
    ],
    "MD": [
      39,
      -76.7
    ],
    "ME": [
      45.4,
      -69
    ],
    "MI": [
      44.3,
      -85.4
    ],
    "MN": [
      46.4,
      -94.6
    ],
    "MO": [
      38.5,
      -92.5
    ],
    "MS": [
      32.7,
      -89.7
    ],
    "NC": [
      35.5,
      -79
    ],
    "NH": [
      43.7,
      -71.5
    ],
    "NJ": [
      40.1,
      -74.5
    ],
    "NM": [
      34.5,
      -106.1
    ],
    "NV": [
      38.5,
      -117
    ],
    "NY": [
      42.9,
      -75.5
    ],
    "OH": [
      40.4,
      -82.8
    ],
    "OK": [
      35.5,
      -97.5
    ],
    "OR": [
      44,
      -120.5
    ],
    "PA": [
      40.9,
      -77.8
    ],
    "RI": [
      41.7,
      -71.5
    ],
    "SC": [
      33.8,
      -81.2
    ],
    "TN": [
      35.8,
      -86.4
    ],
    "TX": [
      31.5,
      -99
    ],
    "UT": [
      39.5,
      -111.5
    ],
    "VA": [
      37.5,
      -78.7
    ],
    "WA": [
      47.4,
      -120.5
    ],
    "WI": [
      44.5,
      -89.5
    ],
    "WV": [
      38.6,
      -80.5
    ],
    "WY": [
      43,
      -107.5
    ]
  },
  "density_table": [
    {
      "st": "AK",
      "name": "Alaska",
      "universe": 32,
      "confirmed": 0,
      "dependent": 32,
      "combined": 32,
      "density": "100.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "HI",
      "name": "Hawaii",
      "universe": 37,
      "confirmed": 0,
      "dependent": 37,
      "combined": 37,
      "density": "100.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "KS",
      "name": "Kansas",
      "universe": 8,
      "confirmed": 0,
      "dependent": 8,
      "combined": 8,
      "density": "100.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MD",
      "name": "Maryland",
      "universe": 52,
      "confirmed": 0,
      "dependent": 51,
      "combined": 51,
      "density": "98.1%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 2,
      "lb": "",
      "deferred": false
    },
    {
      "st": "OR",
      "name": "Oregon",
      "universe": 128,
      "confirmed": 2,
      "dependent": 120,
      "combined": 122,
      "density": "95.3%",
      "indepPct": "1.6%",
      "watch": 0,
      "dec": 2,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "WI",
      "name": "Wisconsin",
      "universe": 237,
      "confirmed": 0,
      "dependent": 124,
      "combined": 124,
      "density": "52.3%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "IA",
      "name": "Iowa",
      "universe": 10,
      "confirmed": 0,
      "dependent": 3,
      "combined": 3,
      "density": "30.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "VA",
      "name": "Virginia",
      "universe": 7,
      "confirmed": 0,
      "dependent": 2,
      "combined": 2,
      "density": "28.6%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "CA",
      "name": "California",
      "universe": 1246,
      "confirmed": 189,
      "dependent": 113,
      "combined": 302,
      "density": "24.2%",
      "indepPct": "15.2%",
      "watch": 2,
      "dec": 4,
      "clo": 9,
      "lb": "",
      "deferred": false
    },
    {
      "st": "CT",
      "name": "Connecticut",
      "universe": 21,
      "confirmed": 4,
      "dependent": 1,
      "combined": 5,
      "density": "23.8%",
      "indepPct": "19.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "IL",
      "name": "Illinois",
      "universe": 132,
      "confirmed": 30,
      "dependent": 1,
      "combined": 31,
      "density": "23.5%",
      "indepPct": "22.7%",
      "watch": 0,
      "dec": 0,
      "clo": 6,
      "lb": "",
      "deferred": false
    },
    {
      "st": "NJ",
      "name": "New Jersey",
      "universe": 86,
      "confirmed": 19,
      "dependent": 0,
      "combined": 19,
      "density": "22.1%",
      "indepPct": "22.1%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MA",
      "name": "Massachusetts",
      "universe": 73,
      "confirmed": 8,
      "dependent": 5,
      "combined": 13,
      "density": "17.8%",
      "indepPct": "11.0%",
      "watch": 0,
      "dec": 1,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "DE",
      "name": "Delaware",
      "universe": 23,
      "confirmed": 4,
      "dependent": 0,
      "combined": 4,
      "density": "17.4%",
      "indepPct": "17.4%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "RI",
      "name": "Rhode Island",
      "universe": 42,
      "confirmed": 4,
      "dependent": 2,
      "combined": 6,
      "density": "14.3%",
      "indepPct": "9.5%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "PA",
      "name": "Pennsylvania",
      "universe": 175,
      "confirmed": 23,
      "dependent": 0,
      "combined": 23,
      "density": "13.1%",
      "indepPct": "13.1%",
      "watch": 0,
      "dec": 0,
      "clo": 2,
      "lb": "",
      "deferred": false
    },
    {
      "st": "ME",
      "name": "Maine",
      "universe": 11,
      "confirmed": 1,
      "dependent": 0,
      "combined": 1,
      "density": "9.1%",
      "indepPct": "9.1%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "OH",
      "name": "Ohio",
      "universe": 323,
      "confirmed": 13,
      "dependent": 14,
      "combined": 27,
      "density": "8.4%",
      "indepPct": "4.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "NY",
      "name": "New York",
      "universe": 350,
      "confirmed": 24,
      "dependent": 4,
      "combined": 28,
      "density": "8.0%",
      "indepPct": "6.9%",
      "watch": 0,
      "dec": 2,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "WA",
      "name": "Washington",
      "universe": 15,
      "confirmed": 1,
      "dependent": 0,
      "combined": 1,
      "density": "6.7%",
      "indepPct": "6.7%",
      "watch": 6,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "DC",
      "name": "Washington, D.C.",
      "universe": 125,
      "confirmed": 7,
      "dependent": 0,
      "combined": 7,
      "density": "5.6%",
      "indepPct": "5.6%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "NM",
      "name": "New Mexico",
      "universe": 98,
      "confirmed": 3,
      "dependent": 0,
      "combined": 3,
      "density": "3.1%",
      "indepPct": "3.1%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "LA",
      "name": "Louisiana",
      "universe": 139,
      "confirmed": 4,
      "dependent": 0,
      "combined": 4,
      "density": "2.9%",
      "indepPct": "2.9%",
      "watch": 0,
      "dec": 1,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MI",
      "name": "Michigan",
      "universe": 373,
      "confirmed": 10,
      "dependent": 0,
      "combined": 10,
      "density": "2.7%",
      "indepPct": "2.7%",
      "watch": 1,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MN",
      "name": "Minnesota",
      "universe": 309,
      "confirmed": 8,
      "dependent": 0,
      "combined": 8,
      "density": "2.6%",
      "indepPct": "2.6%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "FL",
      "name": "Florida",
      "universe": 730,
      "confirmed": 5,
      "dependent": 3,
      "combined": 8,
      "density": "1.1%",
      "indepPct": "0.7%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "AZ",
      "name": "Arizona",
      "universe": 562,
      "confirmed": 4,
      "dependent": 0,
      "combined": 4,
      "density": "0.7%",
      "indepPct": "0.7%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "AR",
      "name": "Arkansas",
      "universe": 109,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "CO",
      "name": "Colorado",
      "universe": 260,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 9,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "GA",
      "name": "Georgia",
      "universe": 94,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MO",
      "name": "Missouri",
      "universe": 81,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 1,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "NH",
      "name": "New Hampshire",
      "universe": 33,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "WV",
      "name": "West Virginia",
      "universe": 8,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "AL",
      "name": "Alabama",
      "universe": 23,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "ID",
      "name": "Idaho",
      "universe": 84,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "IN",
      "name": "Indiana",
      "universe": 132,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "MS",
      "name": "Mississippi",
      "universe": 10,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "NV",
      "name": "Nevada",
      "universe": 104,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "NC",
      "name": "North Carolina",
      "universe": 213,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "OK",
      "name": "Oklahoma",
      "universe": 73,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "SC",
      "name": "South Carolina",
      "universe": 104,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "TN",
      "name": "Tennessee",
      "universe": 112,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "TX",
      "name": "Texas",
      "universe": 1056,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "UT",
      "name": "Utah",
      "universe": 141,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "WY",
      "name": "Wyoming",
      "universe": 8,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    }
  ],
  "jurisdiction_data": {},
  "stateReports": {
    "AK": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/AK_State_Research_Report.pdf"
    },
    "AR": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/AR_State_Research_Report.pdf"
    },
    "AZ": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/AZ_State_Research_Report.pdf"
    },
    "CA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/CA_State_Research_Report.pdf"
    },
    "CO": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/CO_State_Research_Report.pdf"
    },
    "CT": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/CT_State_Research_Report.pdf"
    },
    "DC": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/DC_State_Research_Report.pdf"
    },
    "DE": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/DE_State_Research_Report.pdf"
    },
    "FL": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/FL_State_Research_Report.pdf"
    },
    "GA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/GA_State_Research_Report.pdf"
    },
    "HI": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/HI_State_Research_Report.pdf"
    },
    "IA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/IA_State_Research_Report.pdf"
    },
    "IL": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/IL_State_Research_Report.pdf"
    },
    "KS": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/KS_State_Research_Report.pdf"
    },
    "LA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/LA_State_Research_Report.pdf"
    },
    "MA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/MA_State_Research_Report.pdf"
    },
    "MD": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/MD_State_Research_Report.pdf"
    },
    "ME": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/ME_State_Research_Report.pdf"
    },
    "MI": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/MI_State_Research_Report.pdf"
    },
    "MN": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/MN_State_Research_Report.pdf"
    },
    "MO": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/MO_State_Research_Report.pdf"
    },
    "NH": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/NH_State_Research_Report.pdf"
    },
    "NJ": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/NJ_State_Research_Report.pdf"
    },
    "NM": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/NM_State_Research_Report.pdf"
    },
    "NY": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/NY_State_Research_Report.pdf"
    },
    "OH": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/OH_State_Research_Report.pdf"
    },
    "OR": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/OR_State_Research_Report.pdf"
    },
    "PA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/PA_State_Research_Report.pdf"
    },
    "RI": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/RI_State_Research_Report.pdf"
    },
    "VA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/VA_State_Research_Report.pdf"
    },
    "WA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/WA_State_Research_Report.pdf"
    },
    "WI": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/WI_State_Research_Report.pdf"
    },
    "WV": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/reports/WV_State_Research_Report.pdf"
    }
  },
  "stateK12Enrollment": {
    "AK": 126000,
    "AL": 726000,
    "AR": 476000,
    "IA": 470000,
    "ID": 299000,
    "IN": 1018000,
    "KS": 468000,
    "MS": 437000,
    "NC": 1360000,
    "NH": 172000,
    "NV": 489000,
    "OK": 694000,
    "SC": 776000,
    "TN": 1013000,
    "UT": 680000,
    "VA": 1252000,
    "WV": 250000,
    "WY": 91000
  },
  "charterEnrollment": {
    "confirmedEnrollment": 241139,
    "dependentEnrollment": 183295,
    "combinedEnrollment": 424434,
    "organizingEnrollment": 9608,
    "totalTrackedEnrollment": 1244371,
    "enrollmentDensity": "34.1%",
    "schoolsWithEnrollment": 2486
  },
  "status_lists": {}
};

// NAPCS_REGISTRY_CONTENT — preserved from prior version
/**
 * NAPCS_REGISTRY_CONTENT
 * Drives the Registry tab panel in the dashboard.
 */
var NAPCS_REGISTRY_CONTENT = {
  "version": "v130",
  "lastUpdated": "June 16, 2026",
  "narrative": {
    "projectOverview": {
      "title": "Project Overview",
      "body": "The Charter School Registry is the foundational infrastructure for the NAPCS Unionization Research Project. It provides a complete, authoritative directory of charter schools across all research states — now at Registry v130, covering 7,888 verified open charter schools across 45 jurisdictions. The registry is enriched with authorizer data, labor board jurisdiction assignments, NCES ID crosswalk, geographic coordinates, school enrollment data from NCES CCD 2024–25, and union status findings from the research program. All jurisdictions with open charter schools are now included in the research universe."
    },
    "scope": {
      "title": "Scope",
      "body": "The Registry currently covers 24 states plus the District of Columbia, comprising 5,760 charter schools. Colorado and Washington are included in the registry but research sessions have not yet been conducted for those states. Coverage expands as new state research sessions are initiated — states are added to the registry before research begins, providing the school list that drives each state's labor board search protocol."
    },
    "methodology": {
      "title": "Methodology",
      "body": "The Registry is built on the NCES Common Core of Data (CCD) public school universe files for 2024–25 (released December 2025), filtered to charter schools. Each record is enriched through a multi-step process: authorizer identification and type classification, charter type determination (independent, CMO, dependent/instrumentality), labor board jurisdiction assignment, geographic coordinate verification, school enrollment data from the 2024–25 CCD universe, and website research conducted as part of the research program. Records are matched to NAPCS school IDs where applicable."
    },
    "dataSources": {
      "title": "Data Sources",
      "body": "Primary source: NCES CCD 2024–25 Public Elementary/Secondary School Universe Survey (released December 2025). This is the current vintage used for school enrollment figures (enrollment_2425 field) and school universe counts throughout the dashboard. Supplemental sources include state education agency charter school directories, authorizer websites, and geocoding services for coordinate verification. Union status is sourced exclusively from research staff primary research — labor board portal searches and school-level verification. CBA document links, where publicly available, are recorded in the registry and displayed in the school popup on the dashboard."
    },
    "challenges": {
      "title": "Key Data Challenges",
      "body": "Key data quality challenges include: schools that operate under a different legal entity than their common name, requiring name variant searches at labor boards; schools recently authorized that may not yet have NCES IDs assigned (flagged in the registry); the Carmen/Rocketship Wisconsin authorizer transition, where new NCES IDs are expected as schools are re-authorized under UWM; multi-campus CMO networks where labor cases are filed under the network employer name rather than individual campuses; and schools that have undergone authorizer transitions that change their jurisdiction type. A website gap-fill effort is currently underway for all completed research states. Where data gaps are identified, research staff may recommend targeted outreach to the relevant labor board or state education agency."
    },
    "architecture": {
      "title": "Dashboard Architecture",
      "body": "The Registry feeds the dashboard through seven regional JavaScript data files rebuilt from the master registry spreadsheet: napcs_schools_ca.js (California), napcs_schools_fl.js (Florida), napcs_schools_tx.js (Texas — placeholder for future research), napcs_schools_east.js, napcs_schools_midwest.js, napcs_schools_west.js, and napcs_schools_central.js. Each file covers a geographic cluster of states. Every school record includes an enrollment_2425 field sourced from the NCES CCD 2024–25 universe, enabling per-school enrollment display and state-level charter enrollment rollups. This regional architecture replaced the prior single napcs_schools.js file."
    }
  },
  "about": {
    "keyStats": [
      {
        "label": "Total census schools",
        "value": "7,888"
      },
      {
        "label": "Jurisdictions covered",
        "value": "45 jurisdictions (all charter states + DC, excl. KY)"
      },
      {
        "label": "Data currency date",
        "value": "June 16, 2026"
      },
      {
        "label": "Registry version",
        "value": "v130"
      },
      {
        "label": "Data vintage",
        "value": "NCES CCD 2024–25"
      },
      {
        "label": "Deferred jurisdictions",
        "value": "12 states deferred — PDR-018: AL, ID, IN, MS, NC, NV, OK, SC, TN, TX, UT, WY"
      }
    ]
  },
  "discovery": {
    "title": "Discovery Schools Program",
    "purpose": "The Discovery program documents charter schools outside the NAPCS research universe that are found to have organized staff during the course of registry sweeps and labor board research. These schools are tracked separately and require explicit approval before entering the dataset.",
    "approach": [
      "Schools identified during labor board sweeps that are not in the NAPCS school list are flagged as Discovery candidates.",
      "Each Discovery school is reviewed against the NAPCS universe criteria before approval.",
      "Approved Discovery schools receive a NAPCS-ADD ID assignment and are entered into the Environment Scan Findings tab — not the main dataset — pending sponsor review.",
      "Discovery schools confirmed organized through the approval gate are reported to the executive sponsor for a disposition decision."
    ],
    "keyStats": [
      {
        "label": "Discovery schools found (all states)",
        "value": "See state research reports"
      },
      {
        "label": "Approval gate",
        "value": "Sponsor sign-off required"
      },
      {
        "label": "ID scheme",
        "value": "NAPCS-ADD-[state]-[seq]"
      }
    ]
  }
};