// napcs_config.js — National Configuration & Summary Data
// PLT Strategies Group, Inc. | NAPCS Unionization Research Project
// Auto-generated by NAPCS_Dashboard_School_Builder_v2.js
// Data Currency Date: June 16, 2026
// National denominator: 7,888 open schools (PDR-020)
// Schema: napcsStatus / napcsSubStatus — census methodology framing
// DO NOT EDIT MANUALLY — rebuild from source files

var NAPCS_CONFIG = {
  "national": {
    "universe": 7888,
    "confirmed": 363,
    "dependent": 520,
    "combined": 883,
    "density": "11.2%",
    "confirmed_density": "4.6%",
    "dependent_density": "6.6%",
    "organizing": 18,
    "decertified": 11,
    "closed": 26,
    "jurisdictions": 33,
    "dataDate": "June 16, 2026",
    "denominatorNote": "Registry-verified open schools only (PDR-020, locked June 11, 2026)"
  },
  "state_data": {
    "AK": {
      "name": "Alaska",
      "universe": 32,
      "conf": 0,
      "dep": 32,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "100.0%",
      "lb": "ALRA (AK)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Alaska has no right-to-work statute. AS 23.40 (PERA) and AS 14.03.270 govern public employee labor relations without RTW restriction.",
        "effectiveDate": "N/A",
        "notes": "Alaska is not a right-to-work state. Charter school teachers covered by district CBAs under AS 14.03.270(b) are subject to the full terms of the district NEA-Alaska CBA, which may include union security provisions."
      },
      "note": "",
      "deferred": false
    },
    "AL": {
      "name": "Alabama",
      "universe": 23,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R10",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Ala. Code §25-7-30 through §25-7-36",
        "effectiveDate": "1953",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "AR": {
      "name": "Arkansas",
      "universe": 109,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "National Labor Relations Board — Region 15 (New Orleans)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Arkansas Constitution Amendment 34 (1944); Ark. Code Ann. §11-3-303 et seq.",
        "effectiveDate": "1944-01-01",
        "notes": "Arkansas was the first state to adopt right-to-work via constitutional amendment (1944) — the longest-standing RTW state in the NAPCS dataset. Employees at any organized AR charter school cannot be required to join a union or pay dues as a condition of employment."
      },
      "note": "",
      "deferred": false
    },
    "AZ": {
      "name": "Arizona",
      "universe": 562,
      "conf": 4,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.7%",
      "lb": "NLRB Region 28 (Phoenix)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "A.R.S. §23-1302",
        "effectiveDate": "1947",
        "notes": "Right-to-work state. Applies to private-sector workers under NLRA."
      },
      "note": "",
      "deferred": false
    },
    "CA": {
      "name": "California",
      "universe": 1246,
      "conf": 189,
      "dep": 113,
      "org": 2,
      "dec": 4,
      "clo": 9,
      "watch": 2,
      "density": "24.2%",
      "lb": "PERB(CA) — California Public Employment Relations Board",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Gov. Code §3540 et seq. (EERA)",
        "effectiveDate": "",
        "notes": "Not a right-to-work state. EERA governs public-sector charter employers."
      },
      "note": "",
      "deferred": false
    },
    "CO": {
      "name": "Colorado",
      "universe": 260,
      "conf": 0,
      "dep": 0,
      "org": 9,
      "dec": 0,
      "clo": 0,
      "watch": 9,
      "density": "0.0%",
      "lb": "NLRB R27",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Colorado has no right-to-work statute. The Colorado Labor Peace Act (CRS §§ 8-3-101 et seq.) governs private-sector labor relations but does not include right-to-work provisions. Union security provisions are available in collective bargaining agreements for private-sector employers.",
        "effectiveDate": "N/A",
        "notes": "CO charter schools are private employers under the NLRA. Union security clauses are permissible."
      },
      "note": "",
      "deferred": false
    },
    "CT": {
      "name": "Connecticut",
      "universe": 21,
      "conf": 4,
      "dep": 1,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "23.8%",
      "lb": "SBLR (CT)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Connecticut has no right-to-work statute. Conn. Gen. Stat. §31-101 et seq. (Connecticut Labor Relations Act) and TNA (§10-153a et seq.) permit union security provisions.",
        "effectiveDate": "N/A",
        "notes": "Agency fee and union security clauses are available in both TNA and NLRB-governed CBAs in Connecticut."
      },
      "note": "",
      "deferred": false
    },
    "DC": {
      "name": "Washington, D.C.",
      "universe": 125,
      "conf": 7,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "5.6%",
      "lb": "NLRB",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Washington DC is not a right-to-work jurisdiction. DC charter schools are private employers under the NLRA; no DC right-to-work statute exists and the NLRA preempts any such provision.",
        "effectiveDate": "N/A",
        "notes": "Union security provisions are available in CBA negotiations for DC charter school unions."
      },
      "note": "",
      "deferred": false
    },
    "DE": {
      "name": "Delaware",
      "universe": 23,
      "conf": 4,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "17.4%",
      "lb": "PERB(DE)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Delaware has no right-to-work statute. DE charter school employees are public employees under 14 Del.C. Chapter 40; PERB(DE) has jurisdiction. Union security provisions are standard in public-sector CBAs.",
        "effectiveDate": "N/A",
        "notes": "No right-to-work statute applies. All DE charter schools are public employers — NLRA and any RTW provisions are inapplicable."
      },
      "note": "",
      "deferred": false
    },
    "FL": {
      "name": "Florida",
      "universe": 730,
      "conf": 5,
      "dep": 3,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "1.1%",
      "lb": "PERC (FL)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Art. X §12, Florida Constitution",
        "effectiveDate": null,
        "notes": "Florida is a right-to-work state by constitutional provision. Union security clauses (mandatory dues/fees) are not available for FL charter school unions. SB256 (2023) added annual recertification requirements for public-sector unions falling below 60% dues-paying membership. Right-to-work applies to PERC(FL)-jurisdiction charter schools as public employers and to any NLRB-jurisdiction charter schools as private employers."
      },
      "note": "",
      "deferred": false
    },
    "GA": {
      "name": "Georgia",
      "universe": 94,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R10 (Atlanta)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Georgia Code §34-6-6 — right-to-work statute enacted 1947. Union security agreements (union shop, agency fee) are not available for any employer-employee relationship in Georgia, including NLRB-jurisdiction charter schools.",
        "effectiveDate": "1947",
        "notes": "Right-to-work status means that even if a GA charter school were certified, union security clauses would be unavailable in CBA negotiations."
      },
      "note": "",
      "deferred": false
    },
    "HI": {
      "name": "Hawaii",
      "universe": 37,
      "conf": 0,
      "dep": 37,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "100.0%",
      "lb": "HLRB (HI)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "HRS Art. XIII §2; HRS Ch. 89",
        "effectiveDate": "",
        "notes": "Not a right-to-work state. Strong public-sector bargaining rights under HRS Chapter 89."
      },
      "note": "",
      "deferred": false
    },
    "IA": {
      "name": "Iowa",
      "universe": 10,
      "conf": 0,
      "dep": 3,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "30.0%",
      "lb": "Dual jurisdiction: NLRB R33 (Track A) / Iowa PERA Iowa Code §20 (Track B)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Iowa Code Ch. 731 (Iowa Right to Work Act)",
        "effectiveDate": "1947-01-01",
        "notes": "Iowa has been right-to-work since 1947. Applies to Track A schools. Track B schools are public employers under Iowa PERA — RTW does not apply in the same way but Iowa PERA was significantly restricted in 2017 (mandatory subjects of bargaining limited to base wages only)."
      },
      "note": "",
      "deferred": false
    },
    "ID": {
      "name": "Idaho",
      "universe": 84,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R19",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Idaho Code §44-2101 through §44-2104",
        "effectiveDate": "1985",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "IL": {
      "name": "Illinois",
      "universe": 132,
      "conf": 30,
      "dep": 1,
      "org": 0,
      "dec": 0,
      "clo": 6,
      "watch": 0,
      "density": "23.5%",
      "lb": "NLRB (Region 13) / IELRB",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Illinois has no right-to-work statute.",
        "effectiveDate": null,
        "notes": "Applies to both NLRB (private-sector charters) and IELRB (public-employer charters). Union security agreements are permissible in both jurisdictions."
      },
      "note": "",
      "deferred": false
    },
    "IN": {
      "name": "Indiana",
      "universe": 132,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "IEERB/NLRB R25",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Ind. Code §22-6-6",
        "effectiveDate": "2012",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "KS": {
      "name": "Kansas",
      "universe": 8,
      "conf": 0,
      "dep": 8,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "100.0%",
      "lb": "Kansas Department of Labor — Labor Relations Division (PNA/PERB)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "K.S.A. 44-831 (Kansas Labor-Management Relations Act, Article 8)",
        "effectiveDate": "1958-01-01",
        "notes": "Kansas has been right-to-work since 1958. Applies to any NLRB private employer organizing — though KS charter schools are public employers under the PNA (K.S.A. 72-2218 et seq.), RTW principles do not apply in the same way to PNA-covered employees. Under PNA, no employee can be required to join a professional association."
      },
      "note": "",
      "deferred": false
    },
    "LA": {
      "name": "Louisiana",
      "universe": 139,
      "conf": 4,
      "dep": 0,
      "org": 0,
      "dec": 1,
      "clo": 1,
      "watch": 0,
      "density": "2.9%",
      "lb": "LSCSC / NLRB R15",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "La. R.S. §23:982",
        "effectiveDate": null,
        "notes": "Louisiana is a right-to-work state. Union security clauses are not available for LA charter school unions. Applies to Type 1/3/3B OPSB-authorized schools under NLRB jurisdiction as private employers. Type 2/5 schools under Act 172 LSCSC routing have no established collective bargaining procedure as of June 2026."
      },
      "note": "",
      "deferred": false
    },
    "MA": {
      "name": "Massachusetts",
      "universe": 73,
      "conf": 8,
      "dep": 5,
      "org": 0,
      "dec": 1,
      "clo": 1,
      "watch": 0,
      "density": "17.8%",
      "lb": "DLR (MA)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Massachusetts has no right-to-work statute. MA charter school employees are classified as public employees under M.G.L. c. 71 §89(y) and bargain under M.G.L. c. 150E. Agency fee provisions are available in collective bargaining agreements.",
        "effectiveDate": "N/A",
        "notes": "No right-to-work statute applies to any MA charter school employer or employee."
      },
      "note": "",
      "deferred": false
    },
    "MD": {
      "name": "Maryland",
      "universe": 52,
      "conf": 0,
      "dep": 51,
      "org": 0,
      "dec": 0,
      "clo": 2,
      "watch": 0,
      "density": "98.1%",
      "lb": "PERB (MD)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Md. Ed. Article §9-108; Md. Labor & Employment",
        "effectiveDate": "",
        "notes": "Not a right-to-work state. All charter schools BLANKET_DEPENDENT under §9-108."
      },
      "note": "",
      "deferred": false
    },
    "ME": {
      "name": "Maine",
      "universe": 11,
      "conf": 1,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "9.1%",
      "lb": "NLRB",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Maine has no right-to-work statute. Maine is a private-sector state under NLRA jurisdiction for charter schools; union security provisions are available in CBA negotiations.",
        "effectiveDate": "N/A",
        "notes": "No right-to-work statute applies to ME charter schools."
      },
      "note": "",
      "deferred": false
    },
    "MI": {
      "name": "Michigan",
      "universe": 373,
      "conf": 10,
      "dep": 0,
      "org": 1,
      "dec": 0,
      "clo": 0,
      "watch": 1,
      "density": "2.7%",
      "lb": "MERC / NLRB Region 7",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Mich. Comp. Laws §423.14 (enacted 2012, effective 2013; repealed February 2024 for private-sector NLRB-jurisdiction employers)",
        "effectiveDate": "2013 (enacted); repealed February 2024 for NLRB-jurisdiction",
        "notes": "Michigan enacted right-to-work in 2012 (effective March 2013). Michigan voters passed Proposition 22 in November 2022 repealing right-to-work for private-sector workers; repeal took effect February 2024. NLRB-jurisdiction charter schools (privately incorporated) are now no longer subject to right-to-work — new CBAs may include union security clauses. MERC-jurisdiction charter schools (public employers) were never subject to right-to-work; PERA governs. RTW status: effectively NO for NLRB-jurisdiction charters as of February 2024; never applied to MERC-jurisdiction charters."
      },
      "note": "",
      "deferred": false
    },
    "MN": {
      "name": "Minnesota",
      "universe": 309,
      "conf": 8,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "2.6%",
      "lb": "BMS (MN)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Minnesota has no right-to-work statute. Right-to-work legislation has been proposed in the Minnesota Legislature but has not been enacted. MN charter school employees are public employees under PELRA (Minn. Stat. §179A) following the 2023 amendments; union security provisions are available in collective bargaining agreements.",
        "effectiveDate": "N/A",
        "notes": "RTW legislation proposed but not enacted as of May 2026."
      },
      "note": "",
      "deferred": false
    },
    "MO": {
      "name": "Missouri",
      "universe": 81,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 1,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R14 (St. Louis) + NLRB R17 (Kansas City)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Missouri right-to-work law (RSMo §290.590, enacted 2017) was rejected by voter referendum August 7, 2018 (67% opposed). Missouri has no operative right-to-work statute. Union security provisions are available in collective bargaining agreements.",
        "effectiveDate": "N/A — RTW law repealed by referendum August 2018",
        "notes": "Missouri voters rejected right-to-work 67-33% in August 2018. The 2017 statute never took effect. Union security clauses are available in MO charter school CBAs under NLRA."
      },
      "note": "",
      "deferred": false
    },
    "MS": {
      "name": "Mississippi",
      "universe": 10,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R15",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Miss. Code Ann. §71-1-47",
        "effectiveDate": "1954",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "NC": {
      "name": "North Carolina",
      "universe": 213,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R11",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "N.C. Gen. Stat. §95-78 through §95-84",
        "effectiveDate": "1947",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "NH": {
      "name": "New Hampshire",
      "universe": 33,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "PELRB (NH)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "New Hampshire has no right-to-work statute. RSA 273-A and RSA 194-B govern NH public employee labor relations without RTW restriction.",
        "effectiveDate": "N/A",
        "notes": "NH charter school teachers are public employees under PELRB. Union security provisions are permissible under NH public employee law. NH is not a right-to-work state."
      },
      "note": "",
      "deferred": false
    },
    "NJ": {
      "name": "New Jersey",
      "universe": 86,
      "conf": 19,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "22.1%",
      "lb": "PERC (NJ)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "New Jersey has no right-to-work statute.",
        "effectiveDate": null,
        "notes": "NJ charter school employees are public employees under PERC(NJ) jurisdiction (EERA). Right-to-work statutes apply only to private-sector NLRA employers. Not applicable to NJ charter schools."
      },
      "note": "",
      "deferred": false
    },
    "NM": {
      "name": "New Mexico",
      "universe": 98,
      "conf": 3,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "3.1%",
      "lb": "PELRB (confirmed for J Paul Taylor Academy) / CONTESTED PELRB or NLRB Region 28 (other schools)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "N.M. Stat. Ann. §50-11-1 et seq.",
        "effectiveDate": "",
        "notes": "Not a right-to-work state. Jurisdictional ambiguity between PELRB and NLRB R28 for charter schools."
      },
      "note": "",
      "deferred": false
    },
    "NV": {
      "name": "Nevada",
      "universe": 104,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "EMRB(NV)/NLRB R28",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "",
        "effectiveDate": "",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "NY": {
      "name": "New York",
      "universe": 350,
      "conf": 24,
      "dep": 4,
      "org": 0,
      "dec": 2,
      "clo": 0,
      "watch": 0,
      "density": "8.0%",
      "lb": "PERB(NY)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "New York has no right-to-work statute.",
        "effectiveDate": null,
        "notes": "NY charter school employees are statutory public employees under Education Law Article 56 (Taylor Law jurisdiction). Right-to-work statutes apply only to private-sector NLRA employers. PERB(NY)-jurisdiction schools are public employers and not subject to right-to-work. NLRB-jurisdiction independently incorporated NY charters are private employers — no right-to-work statute applies in New York."
      },
      "note": "",
      "deferred": false
    },
    "OH": {
      "name": "Ohio",
      "universe": 323,
      "conf": 13,
      "dep": 14,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "8.4%",
      "lb": "NLRB (Region 8 / Region 9)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Ohio has no right-to-work statute for private-sector employees. NLRA preempts state right-to-work law for private employers, and Ohio has enacted no such statute. Ohio public employees retain full collective bargaining rights under ORC Chapter 4117 (SB 5, enacted 2011, was repealed by voter referendum November 2011).",
        "effectiveDate": "N/A",
        "notes": "No right-to-work statute applies to Ohio charter schools, which are private employers under the NLRA. Union security provisions (agency fee, union shop) are available in CBA negotiations."
      },
      "note": "",
      "deferred": false
    },
    "OK": {
      "name": "Oklahoma",
      "universe": 73,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R17",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Okla. Stat. tit. 40, §§481-490",
        "effectiveDate": "2001",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "OR": {
      "name": "Oregon",
      "universe": 128,
      "conf": 2,
      "dep": 120,
      "org": 0,
      "dec": 2,
      "clo": 0,
      "watch": 0,
      "density": "95.3%",
      "lb": "ERB (OR)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Oregon has no right-to-work statute.",
        "effectiveDate": null,
        "notes": "Oregon is a non-right-to-work state. ORS Chapter 243 (PECBA) governs public employer charter schools (ERB jurisdiction). Union security clauses are permissible. Independently incorporated OR charter schools that are private employers under NLRA (NLRB jurisdiction) are also not subject to right-to-work — no Oregon right-to-work statute exists for either jurisdiction."
      },
      "note": "",
      "deferred": false
    },
    "PA": {
      "name": "Pennsylvania",
      "universe": 175,
      "conf": 23,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 2,
      "watch": 0,
      "density": "13.1%",
      "lb": "NLRB",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Pennsylvania has no right-to-work statute. Right-to-work legislation has been introduced in the Pennsylvania General Assembly but has not been enacted. PA charter school employees are private-sector employees under the NLRA; union security provisions are available in collective bargaining agreements.",
        "effectiveDate": "N/A",
        "notes": "RTW legislation has been proposed but not enacted as of May 2026."
      },
      "note": "",
      "deferred": false
    },
    "RI": {
      "name": "Rhode Island",
      "universe": 42,
      "conf": 4,
      "dep": 2,
      "org": 0,
      "dec": 0,
      "clo": 1,
      "watch": 0,
      "density": "14.3%",
      "lb": "NLRB Region 1 (Boston)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Rhode Island has no right-to-work statute. RI charter school employees are private-sector employees under the NLRA; union security provisions are available in CBA negotiations.",
        "effectiveDate": "N/A",
        "notes": "The unresolved question in RI is whether the state teacher strike prohibition (applicable to public-sector educators under RIPLRA) applies to NLRB-organized charter school employees. Federal court proceedings pending as of May 2026."
      },
      "note": "",
      "deferred": false
    },
    "SC": {
      "name": "South Carolina",
      "universe": 104,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R11",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "S.C. Code Ann. §41-7-10 through §41-7-90",
        "effectiveDate": "1954",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "TN": {
      "name": "Tennessee",
      "universe": 112,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R10",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Tenn. Code Ann. §50-1-201",
        "effectiveDate": "1947",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "TX": {
      "name": "Texas",
      "universe": 1056,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R16",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Tex. Lab. Code §101.052 through §101.053",
        "effectiveDate": "1993",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "UT": {
      "name": "Utah",
      "universe": 141,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R28",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Utah Code Ann. §34-34-1 through §34-34-17",
        "effectiveDate": "1955",
        "notes": ""
      },
      "note": "",
      "deferred": true
    },
    "VA": {
      "name": "Virginia",
      "universe": 7,
      "conf": 0,
      "dep": 2,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "28.6%",
      "lb": "Dual jurisdiction: Va. Code §40.1-57.2 (district CB law, 2 schools) / NLRB R5 Baltimore (5 schools)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Virginia Code §40.1-58 et seq. (Virginia Right to Work Act)",
        "effectiveDate": "1947-01-01",
        "notes": "Virginia has been right-to-work since 1947. Employees at any organized VA charter school cannot be required to join a union or pay dues as a condition of employment. Applies to both NLRB private employer schools and schools covered by the Va. Code §40.1-57.2 state CB framework."
      },
      "note": "",
      "deferred": false
    },
    "WA": {
      "name": "Washington",
      "universe": 15,
      "conf": 1,
      "dep": 0,
      "org": 6,
      "dec": 0,
      "clo": 0,
      "watch": 6,
      "density": "6.7%",
      "lb": "PERC (WA)",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Washington has no right-to-work statute. RCW 41.56.0251 classifies WA charter school employees as public employees under PECBA — union security provisions are standard in WA public employee collective bargaining agreements.",
        "effectiveDate": "N/A",
        "notes": "WA charter school employees are public employees under RCW 41.56.0251 (SB 6194, 2016). PERC (Public Employment Relations Commission) has exclusive jurisdiction. Public employee union security is standard in WA."
      },
      "note": "",
      "deferred": false
    },
    "WI": {
      "name": "Wisconsin",
      "universe": 237,
      "conf": 0,
      "dep": 124,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "52.3%",
      "lb": "WERC (WI) / NLRB R18",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "NO",
        "basis": "Wisconsin right-to-work (Wis. Stat. §111.04) applies to private-sector NLRA employers only. Does not apply to WERC-jurisdiction public employers.",
        "effectiveDate": "2015",
        "notes": "WI enacted right-to-work for private-sector employees in 2015 (Wis. Stat. §111.04). All 124 DEPENDENT WI charter schools are LEA instrumentalities — public employers under WERC jurisdiction (MERA). Right-to-work does not apply to WERC-jurisdiction schools. NLRB R18 non-instrumentality charters are private employers and are subject to right-to-work; union security clauses are not available."
      },
      "note": "",
      "deferred": false
    },
    "WV": {
      "name": "West Virginia",
      "universe": 8,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R9",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "WV Code §21-1A-1 et seq. (West Virginia Workplace Freedom Act, effective July 1, 2016)",
        "effectiveDate": "2016-07-01",
        "notes": "WV right-to-work applies to all collective bargaining contracts entered into, modified, renewed, or extended after July 1, 2016. Employees cannot be required to join a union or pay dues as a condition of employment. Separately, WV Code §18-5-45a declares that public school district employees have no right to collective bargaining — but this applies to district employees, not charter school employees who organize under NLRB private employer framework."
      },
      "note": "",
      "deferred": false
    },
    "WY": {
      "name": "Wyoming",
      "universe": 8,
      "conf": 0,
      "dep": 0,
      "org": 0,
      "dec": 0,
      "clo": 0,
      "watch": 0,
      "density": "0.0%",
      "lb": "NLRB R27",
      "lb_abbrev": "",
      "lb_full": "",
      "rtw": {
        "status": "YES",
        "basis": "Wyo. Stat. Ann. §27-7-109",
        "effectiveDate": "1963",
        "notes": ""
      },
      "note": "",
      "deferred": true
    }
  },
  "state_centers": {
    "AK": [
      64.2,
      -153
    ],
    "AL": [
      32.8,
      -86.8
    ],
    "AR": [
      34.8,
      -92.2
    ],
    "AZ": [
      34.3,
      -111.1
    ],
    "CA": [
      37.2,
      -119.4
    ],
    "CO": [
      39,
      -105.5
    ],
    "CT": [
      41.6,
      -72.7
    ],
    "DC": [
      38.9,
      -77
    ],
    "DE": [
      39,
      -75.5
    ],
    "FL": [
      28,
      -82.5
    ],
    "GA": [
      32.7,
      -83.5
    ],
    "HI": [
      20.9,
      -157
    ],
    "IA": [
      42,
      -93.5
    ],
    "ID": [
      44,
      -114.5
    ],
    "IL": [
      40,
      -89.2
    ],
    "IN": [
      40,
      -86.1
    ],
    "KS": [
      38.5,
      -98
    ],
    "LA": [
      31,
      -91.8
    ],
    "MA": [
      42.3,
      -71.8
    ],
    "MD": [
      39,
      -76.7
    ],
    "ME": [
      45.4,
      -69
    ],
    "MI": [
      44.3,
      -85.4
    ],
    "MN": [
      46.4,
      -94.6
    ],
    "MO": [
      38.5,
      -92.5
    ],
    "MS": [
      32.7,
      -89.7
    ],
    "NC": [
      35.5,
      -79
    ],
    "NH": [
      43.7,
      -71.5
    ],
    "NJ": [
      40.1,
      -74.5
    ],
    "NM": [
      34.5,
      -106.1
    ],
    "NV": [
      38.5,
      -117
    ],
    "NY": [
      42.9,
      -75.5
    ],
    "OH": [
      40.4,
      -82.8
    ],
    "OK": [
      35.5,
      -97.5
    ],
    "OR": [
      44,
      -120.5
    ],
    "PA": [
      40.9,
      -77.8
    ],
    "RI": [
      41.7,
      -71.5
    ],
    "SC": [
      33.8,
      -81.2
    ],
    "TN": [
      35.8,
      -86.4
    ],
    "TX": [
      31.5,
      -99
    ],
    "UT": [
      39.5,
      -111.5
    ],
    "VA": [
      37.5,
      -78.7
    ],
    "WA": [
      47.4,
      -120.5
    ],
    "WI": [
      44.5,
      -89.5
    ],
    "WV": [
      38.6,
      -80.5
    ],
    "WY": [
      43,
      -107.5
    ]
  },
  "density_table": [
    {
      "st": "AK",
      "name": "Alaska",
      "universe": 32,
      "confirmed": 0,
      "dependent": 32,
      "combined": 32,
      "density": "100.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "HI",
      "name": "Hawaii",
      "universe": 37,
      "confirmed": 0,
      "dependent": 37,
      "combined": 37,
      "density": "100.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "KS",
      "name": "Kansas",
      "universe": 8,
      "confirmed": 0,
      "dependent": 8,
      "combined": 8,
      "density": "100.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MD",
      "name": "Maryland",
      "universe": 52,
      "confirmed": 0,
      "dependent": 51,
      "combined": 51,
      "density": "98.1%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 2,
      "lb": "",
      "deferred": false
    },
    {
      "st": "OR",
      "name": "Oregon",
      "universe": 128,
      "confirmed": 2,
      "dependent": 120,
      "combined": 122,
      "density": "95.3%",
      "indepPct": "1.6%",
      "watch": 0,
      "dec": 2,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "WI",
      "name": "Wisconsin",
      "universe": 237,
      "confirmed": 0,
      "dependent": 124,
      "combined": 124,
      "density": "52.3%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "IA",
      "name": "Iowa",
      "universe": 10,
      "confirmed": 0,
      "dependent": 3,
      "combined": 3,
      "density": "30.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "VA",
      "name": "Virginia",
      "universe": 7,
      "confirmed": 0,
      "dependent": 2,
      "combined": 2,
      "density": "28.6%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "CA",
      "name": "California",
      "universe": 1246,
      "confirmed": 189,
      "dependent": 113,
      "combined": 302,
      "density": "24.2%",
      "indepPct": "15.2%",
      "watch": 2,
      "dec": 4,
      "clo": 9,
      "lb": "",
      "deferred": false
    },
    {
      "st": "CT",
      "name": "Connecticut",
      "universe": 21,
      "confirmed": 4,
      "dependent": 1,
      "combined": 5,
      "density": "23.8%",
      "indepPct": "19.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "IL",
      "name": "Illinois",
      "universe": 132,
      "confirmed": 30,
      "dependent": 1,
      "combined": 31,
      "density": "23.5%",
      "indepPct": "22.7%",
      "watch": 0,
      "dec": 0,
      "clo": 6,
      "lb": "",
      "deferred": false
    },
    {
      "st": "NJ",
      "name": "New Jersey",
      "universe": 86,
      "confirmed": 19,
      "dependent": 0,
      "combined": 19,
      "density": "22.1%",
      "indepPct": "22.1%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MA",
      "name": "Massachusetts",
      "universe": 73,
      "confirmed": 8,
      "dependent": 5,
      "combined": 13,
      "density": "17.8%",
      "indepPct": "11.0%",
      "watch": 0,
      "dec": 1,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "DE",
      "name": "Delaware",
      "universe": 23,
      "confirmed": 4,
      "dependent": 0,
      "combined": 4,
      "density": "17.4%",
      "indepPct": "17.4%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "RI",
      "name": "Rhode Island",
      "universe": 42,
      "confirmed": 4,
      "dependent": 2,
      "combined": 6,
      "density": "14.3%",
      "indepPct": "9.5%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "PA",
      "name": "Pennsylvania",
      "universe": 175,
      "confirmed": 23,
      "dependent": 0,
      "combined": 23,
      "density": "13.1%",
      "indepPct": "13.1%",
      "watch": 0,
      "dec": 0,
      "clo": 2,
      "lb": "",
      "deferred": false
    },
    {
      "st": "ME",
      "name": "Maine",
      "universe": 11,
      "confirmed": 1,
      "dependent": 0,
      "combined": 1,
      "density": "9.1%",
      "indepPct": "9.1%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "OH",
      "name": "Ohio",
      "universe": 323,
      "confirmed": 13,
      "dependent": 14,
      "combined": 27,
      "density": "8.4%",
      "indepPct": "4.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "NY",
      "name": "New York",
      "universe": 350,
      "confirmed": 24,
      "dependent": 4,
      "combined": 28,
      "density": "8.0%",
      "indepPct": "6.9%",
      "watch": 0,
      "dec": 2,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "WA",
      "name": "Washington",
      "universe": 15,
      "confirmed": 1,
      "dependent": 0,
      "combined": 1,
      "density": "6.7%",
      "indepPct": "6.7%",
      "watch": 6,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "DC",
      "name": "Washington, D.C.",
      "universe": 125,
      "confirmed": 7,
      "dependent": 0,
      "combined": 7,
      "density": "5.6%",
      "indepPct": "5.6%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "NM",
      "name": "New Mexico",
      "universe": 98,
      "confirmed": 3,
      "dependent": 0,
      "combined": 3,
      "density": "3.1%",
      "indepPct": "3.1%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "LA",
      "name": "Louisiana",
      "universe": 139,
      "confirmed": 4,
      "dependent": 0,
      "combined": 4,
      "density": "2.9%",
      "indepPct": "2.9%",
      "watch": 0,
      "dec": 1,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MI",
      "name": "Michigan",
      "universe": 373,
      "confirmed": 10,
      "dependent": 0,
      "combined": 10,
      "density": "2.7%",
      "indepPct": "2.7%",
      "watch": 1,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MN",
      "name": "Minnesota",
      "universe": 309,
      "confirmed": 8,
      "dependent": 0,
      "combined": 8,
      "density": "2.6%",
      "indepPct": "2.6%",
      "watch": 0,
      "dec": 0,
      "clo": 1,
      "lb": "",
      "deferred": false
    },
    {
      "st": "FL",
      "name": "Florida",
      "universe": 730,
      "confirmed": 5,
      "dependent": 3,
      "combined": 8,
      "density": "1.1%",
      "indepPct": "0.7%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "AZ",
      "name": "Arizona",
      "universe": 562,
      "confirmed": 4,
      "dependent": 0,
      "combined": 4,
      "density": "0.7%",
      "indepPct": "0.7%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "AR",
      "name": "Arkansas",
      "universe": 109,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "CO",
      "name": "Colorado",
      "universe": 260,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 9,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "GA",
      "name": "Georgia",
      "universe": 94,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "MO",
      "name": "Missouri",
      "universe": 81,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 1,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "NH",
      "name": "New Hampshire",
      "universe": 33,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "WV",
      "name": "West Virginia",
      "universe": 8,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": false
    },
    {
      "st": "AL",
      "name": "Alabama",
      "universe": 23,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "ID",
      "name": "Idaho",
      "universe": 84,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "IN",
      "name": "Indiana",
      "universe": 132,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "MS",
      "name": "Mississippi",
      "universe": 10,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "NV",
      "name": "Nevada",
      "universe": 104,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "NC",
      "name": "North Carolina",
      "universe": 213,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "OK",
      "name": "Oklahoma",
      "universe": 73,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "SC",
      "name": "South Carolina",
      "universe": 104,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "TN",
      "name": "Tennessee",
      "universe": 112,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "TX",
      "name": "Texas",
      "universe": 1056,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "UT",
      "name": "Utah",
      "universe": 141,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    },
    {
      "st": "WY",
      "name": "Wyoming",
      "universe": 8,
      "confirmed": 0,
      "dependent": 0,
      "combined": 0,
      "density": "0.0%",
      "indepPct": "0.0%",
      "watch": 0,
      "dec": 0,
      "clo": 0,
      "lb": "",
      "deferred": true
    }
  ],
  "jurisdiction_data": {
    "AK": {
      "lb_abbrev": "ALRA (AK)",
      "lb_full": "Alaska Labor Relations Agency — administers Public Employment Relations Act (PERA, AS 23.40.070–23.40.260)",
      "lb_url": "https://labor.alaska.gov/laborr/home.htm",
      "statute": "AS 14.03.270(b) (charter school CBA carryover — district CBA applies by default to district-employed charter teachers unless district and bargaining unit jointly agree to waiver). AS 14.03.270(d) (charter may also hire non-district employees outside CBA). AS 23.40 (PERA — public employee labor relations). AS 23.40.090 (bargaining unit determination). All AK charter schools are district-authorized programs. District is employer of record for district-employed teachers.",
      "nlrb": "No",
      "nlrb_note": "ALRA (PERA) has exclusive jurisdiction. All AK charter school teachers employed by the authorizing school district are public employees under PERA. NLRB does not apply. AS 14.03.270(d) permits charter schools to separately hire non-district employees — those employees may have different labor status, but no such independent unit has been identified at any AK charter school.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "AR": {
      "lb_abbrev": "National Labor Relations Board — Region 15 (New Orleans)",
      "lb_full": "",
      "lb_url": "https://www.nlrb.gov/about-nlrb/who-we-are/regional-offices/region-15-new-orleans",
      "statute": "",
      "nlrb": "Yes",
      "nlrb_note": "",
      "card_check": "Yes",
      "rtw": true,
      "dominant": "",
      "note": ""
    },
    "AZ": {
      "lb_abbrev": "NLRB Region 28 (Phoenix)",
      "lb_full": "National Labor Relations Board",
      "lb_url": "https://www.nlrb.gov/about-nlrb/who-we-are/regional-offices/region-28-phoenix",
      "statute": "National Labor Relations Act (NLRA). Arizona is a right-to-work state (ARS §23-1302). No state public-sector collective bargaining statute applies to charter schools. NLRB Region 28 has exclusive jurisdiction.",
      "nlrb": "Yes",
      "nlrb_note": "Arizona has no public-sector collective bargaining statute (ARS §23-1302). All AZ charter schools are private employers under NLRA. NLRB Region 28 (Phoenix) has exclusive jurisdiction.",
      "card_check": "No",
      "rtw": true,
      "dominant": "",
      "note": ""
    },
    "CO": {
      "lb_abbrev": "NLRB R27",
      "lb_full": "National Labor Relations Board, Region 27 (Denver)",
      "lb_url": "https://www.nlrb.gov/regions/region-27-denver",
      "statute": "National Labor Relations Act (NLRA), 29 U.S.C. §§ 151 et seq. Colorado Labor Peace Act (LPA), CRS §§ 8-3-101 et seq. — applies to private sector only; school districts and political subdivisions excluded. CRS §22-30.5 et seq. — Colorado Charter Schools Act. CRS §22-30.5-104.9 (enacted May 15, 2023) — Charter schools declared public entities; board directors deemed public servants; subject to oath of office under §24-12-101. SB23-111 (2023) — grants K-12 employees right to organize and present proposals; no mandatory bargaining obligation; no enforcement mechanism; does not override political subdivision question.",
      "nlrb": "Yes",
      "nlrb_note": "JURISDICTIONAL UNCERTAINTY — THE MOST IMPORTANT LABOR LAW QUESTION IN THE CO CHARTER SECTOR: NLRB R27 Regional Director Paula Sawyer dismissed RC petition 27-RC-311273 (KIPP Northeast Denver Leadership Academy, filed Jan 2023) on grounds that CO charter schools are political subdivisions of the state exempt from NLRB jurisdiction. Sawyer found (1) the State Board of Education has power to revoke charters of underperforming schools and (2) the state education commissioner can appoint and remove members of charter school governing boards and change governing documents — satisfying Hawkins Prong 2. Case is Closed with no published Board reversal. CRS §22-30.5-104.9 (2023) further strengthened the political subdivision argument by declaring charter schools public entities and board directors public servants subject to oath of office. IF the political subdivision finding holds: all 266 CO charter schools are exempt from NLRB jurisdiction AND exempt from the Colorado LPA (which excludes political subdivisions). CO charter employees would have no operative mandatory collective bargaining path under any law. This is the defining labor law question for the CO charter sector.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "CT": {
      "lb_abbrev": "SBLR (CT)",
      "lb_full": "Connecticut State Board of Labor Relations",
      "lb_url": "https://portal.ct.gov/SBLR",
      "statute": "Connecticut Teacher Negotiation Act (TNA) — Conn. Gen. Stat. §10-153a et seq. Governs certificated staff in most CT charter schools classified as public employers. SBLR handles prohibited practice complaints; representation via TNA process administered by CT SBE.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB Region 1 (Boston) applies to Common Ground High School (C0997001), independently incorporated as New Haven Ecology Project, Inc. — a private nonprofit employer. All other CT NAPCS schools use TNA/SBLR jurisdiction.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "DC": {
      "lb_abbrev": "NLRB",
      "lb_full": "National Labor Relations Board — Region 5 (Baltimore/Washington)",
      "lb_url": "https://www.nlrb.gov/regions/region-5",
      "statute": "National Labor Relations Act (NLRA). All DC Public Charter Schools (PCS) are authorized by the DC Public Charter School Board (DC PCSB) and independently incorporated as private nonprofit employers. DC PERB covers traditional DCPS employees only — PERB(DC) does NOT apply to any DC PCS. All DC charter labor matters are handled by NLRB Region 5.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB Region 5 (Baltimore) is the sole applicable board for all 7 DC NAPCS charter schools. PERB(DC) covers DCPS employees only. This has been clearly established across all 6 certification proceedings in the DC charter sector.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "DE": {
      "lb_abbrev": "PERB(DE)",
      "lb_full": "Delaware Public Employment Relations Board (PERB)",
      "lb_url": "https://perb.delaware.gov",
      "statute": "14 Del.C. Chapter 40 — Public School Employment Relations Act (PSERA). All Delaware charter schools are public employers. PERB(DE) has exclusive jurisdiction. The NLRB has never claimed jurisdiction over a Delaware charter school. Card-check (majority authorization / BU determination without election) is available under PSERA — confirmed by Sussex Academy cert February 2026 (case 1521, BU Determination).",
      "nlrb": "No",
      "nlrb_note": "NLRB has no jurisdiction over any Delaware charter school. All DE charters are public employers under PSERA (14 Del.C. Ch. 40). Organizing proceeds through PERB(DE) petition → BU Determination → card authorization (card-check) or election → certification.",
      "card_check": "Yes",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "FL": {
      "lb_abbrev": "PERC (FL)",
      "lb_full": "Florida Public Employees Relations Commission",
      "lb_url": null,
      "statute": "Florida Public Employees Relations Act (PERA), Fla. Stat. §447.203. PERC(FL) has exclusive jurisdiction over all FL charter schools — all are public employers. NLRB has no jurisdiction. SB256 (2023) requires annual union recertification if dues-paying membership falls below 60%.",
      "nlrb": "No",
      "nlrb_note": "NLRB has no jurisdiction in Florida. PERC(FL) has exclusive jurisdiction under PERA (Fla. Stat. §447.203). 0 NLRB RC certifications found across 768 FL registry schools. PERC portal accessible at perc.myflorida.com/co/certResults.aspx.",
      "card_check": "No",
      "rtw": true,
      "dominant": "",
      "note": ""
    },
    "GA": {
      "lb_abbrev": "NLRB R10 (Atlanta)",
      "lb_full": "National Labor Relations Board — Region 10 (Atlanta). No state public-sector labor board with charter jurisdiction.",
      "lb_url": "https://www.nlrb.gov/search/case",
      "statute": "O.C.G.A. 20-2-989.10 (\"Nothing in this part shall be construed to permit or foster collective bargaining\") — Georgia is the only state to single out teachers by statute to bar collective bargaining. O.C.G.A. 20-2-2065(b)(1): a charter school is \"a public, nonsectarian, nonreligious, nonprofit school.\" Charter Schools Act of 1998 (O.C.G.A. 20-2-2060 et seq.). Georgia is a right-to-work state.",
      "nlrb": "Yes",
      "nlrb_note": "All GA charter schools are independent nonprofit public schools and private employers under the NLRA. NLRB R10 (Atlanta) is the exclusive labor board. No state labor board has jurisdiction over charter school labor relations. The only documented GA charter NLRB case (GCA 10-CA-357225) is a closed individual coercive-rules ULP, not an organizing case.",
      "card_check": "No",
      "rtw": true,
      "dominant": "",
      "note": ""
    },
    "HI": {
      "lb_abbrev": "HLRB (HI)",
      "lb_full": "Hawaii Labor Relations Board",
      "lb_url": "https://labor.hawaii.gov/hlrb/",
      "statute": "Hawaii Revised Statutes Chapter 89 (Collective Bargaining in Public Employment); HRS §89-10.55 (Charter School Collective Bargaining); HRS Chapter 302D (Charter Schools Act); HRS §302B (Public Charter Schools)",
      "nlrb": "No",
      "nlrb_note": "NLRB does not apply. All 40 HI charter schools are public employers under HRS Chapter 89. HLRB has exclusive jurisdiction. No independently incorporated private nonprofit charter schools exist in Hawaii — sole authorizer is the Hawaii Public Charter School Commission (HPCSC), a state commission. NLRB Region 37 (Honolulu) search conducted May 2026: zero charter school RC/RD petitions or certifications found.",
      "card_check": "Yes",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "IA": {
      "lb_abbrev": "Dual jurisdiction: NLRB R33 (Track A) / Iowa PERA Iowa Code §20 (Track B)",
      "lb_full": "Track A (independently incorporated): National Labor Relations Board — Region 33, Peoria, Illinois. Track B (School Board Model): Iowa Employment Appeals Board (EAB, formerly PERB) administers Iowa PERA for district employees.",
      "lb_url": "https://www.nlrb.gov/regional-office/region-33-peoria",
      "statute": "DUAL TRACK. Track A: National Labor Relations Act (NLRA) — Iowa Code §256E independently incorporated charter schools are private employers under NLRB R33. Track B: Iowa PERA (Iowa Code §20) — School Board Model (CSD*) charter school teachers are employees of the authorizing school district. Iowa school districts are public employers under Iowa Code §20.3. ISEA/NEA affiliates hold teacher agreements at virtually all Iowa districts. District teacher agreements cover CSD* charter school teachers by virtue of district employment.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB R33 (Peoria) applies to Track A independently incorporated charter schools only. Track B School Board Model schools are covered by Iowa PERA, not NLRB.",
      "card_check": "No",
      "rtw": true,
      "dominant": "",
      "note": ""
    },
    "IL": {
      "lb_abbrev": "NLRB (Region 13) / IELRB",
      "lb_full": "National Labor Relations Board, Region 13 (Chicago) — primary jurisdiction for privately incorporated charters. Illinois Educational Labor Relations Board — ISBE-authorized/dependent charters only.",
      "lb_url": "https://www.nlrb.gov/regions/region-13 | https://www.illinois.gov/agencies/elrb",
      "statute": "National Labor Relations Act (NLRA) for private nonprofits (most IL charters, per Chicago Mathematics & Science Academy, 359 NLRB 41, Dec 14 2012). Illinois Educational Labor Relations Act (IELRA, 115 ILCS 5/) for public-employer charters (ISBE-authorized). NOTE: ILRB (Illinois Labor Relations Board) does NOT cover educational employers — never cite ILRB for any charter school.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB jurisdiction applies to all independently incorporated charter nonprofits (the vast majority of IL NAPCS schools). Landmark case: Chicago Mathematics & Science Academy, 359 NLRB 41 (Dec 14 2012). This requires secret ballot election; card-check not available under NLRB.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "KS": {
      "lb_abbrev": "Kansas Department of Labor — Labor Relations Division (PNA/PERB)",
      "lb_full": "",
      "lb_url": "https://www.dol.ks.gov/-/labor-negotiations",
      "statute": "",
      "nlrb": "No",
      "nlrb_note": "",
      "card_check": "No",
      "rtw": true,
      "dominant": "",
      "note": ""
    },
    "LA": {
      "lb_abbrev": "LSCSC / NLRB R15",
      "lb_full": "Louisiana State Civil Service Commission (LSCSC) under LERA [Type 1/3/3B/4, locally-authorized]; NLRB Region 15 New Orleans [Type 2/5 BESE-authorized — pre-Act 172 history only]",
      "lb_url": "https://www.lascsc.org",
      "statute": "Louisiana Employee Relations Act (LERA) — post-Act 172 (signed May 23, 2024) for all BESE-authorized Type 2/5 charters. Pre-Act 172: NLRA / NLRB R15. Locally-authorized (Type 1/3/3B/4) charters: LSCSC/LERA throughout.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB R15 applies to pre-Act 172 history for Type 2/5 BESE-authorized schools only. Post-Act 172 (May 23, 2024): all BESE-authorized charters reclassified as public employers — NLRB R15 affirmed no jurisdiction April 2025, upheld January 2026. Locally-authorized schools (Type 1/3/3B/4): LSCSC/LERA throughout; NLRB does not apply.",
      "card_check": "Yes",
      "rtw": true,
      "dominant": "",
      "note": ""
    },
    "MA": {
      "lb_abbrev": "DLR (MA)",
      "lb_full": "Massachusetts Department of Labor Relations",
      "lb_url": "https://www.mass.gov/orgs/department-of-labor-relations",
      "statute": "M.G.L. c. 71 §89 (Charter School Law — explicitly classifies charter school employees as public employees); M.G.L. c. 150E (Public Employee Collective Bargaining). Card-check (Written Majority Authorization / WMA) available — no election required.",
      "nlrb": "No",
      "nlrb_note": "NLRB does NOT apply to any MA charter school. M.G.L. c. 71 §89(y) explicitly classifies all charter school employees as public employees under DLR(MA) jurisdiction. This is uncontested in MA and has never been successfully challenged.",
      "card_check": "Yes",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "MD": {
      "lb_abbrev": "PERB (MD)",
      "lb_full": "Maryland Public Employee Relations Board",
      "lb_url": "https://laborboard.maryland.gov",
      "statute": "Maryland Education Article §§9-101 et seq. (Public Charter School Act of 2003, 2003 Md. Laws ch. 358); Ed. Article §9-108 (employee status — charter teachers are public school employees of the authorizing district); Ed. Article Title 6, Subtitles 4 and 5 (collective bargaining rights for certificated and non-certificated employees); Maryland PERB consolidated from three prior boards (SLRB, SHELRB, PSLRB) under HB 984 (2023), effective 2024.",
      "nlrb": "No",
      "nlrb_note": "NLRB does not apply to any Maryland charter school. All 52 MD charter schools are authorized exclusively by local school districts (LEAs). Ed. Article §9-108 designates charter teachers as public school employees of the authorizing district — making every MD charter school a public employer under PERB (MD) jurisdiction. No independently incorporated private nonprofit charter pathway exists in Maryland. NLRB Region 4 (Philadelphia) and Region 5 (Baltimore) search conducted May 2026: zero Maryland charter school RC/RD petitions or certifications found.",
      "card_check": "Yes",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "ME": {
      "lb_abbrev": "NLRB",
      "lb_full": "National Labor Relations Board — Region 1 (Boston)",
      "lb_url": "https://www.nlrb.gov/regions/region-1",
      "statute": "National Labor Relations Act (NLRA). Baxter Academy is incorporated as a private nonprofit charter school under the Maine Charter School Commission — it is not a public employer and falls under NLRB, not MLRB. MLRB (Maine Labor Relations Board) governs traditional public employers only and does NOT apply to Baxter Academy.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB Region 1 (Boston) is the sole applicable labor board for Baxter Academy. Case 01-RC-239165.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "MI": {
      "lb_abbrev": "MERC / NLRB Region 7",
      "lb_full": "Michigan Employment Relations Commission (MERC) — primary for locally/ISD-authorized charters; National Labor Relations Board Region 7 (Detroit) — for independently incorporated nonprofits",
      "lb_url": "https://miemprels.my.site.com",
      "statute": "SPLIT JURISDICTION: (1) MERC under PERA (Mich. Comp. Laws §423.201 et seq.) for locally-authorized and ISD-authorized charter schools (public employers); (2) NLRB Region 7 (Detroit, prefix \"07-\") for privately incorporated charter nonprofits under NLRA. Authorizer type is the determinative factor — same pattern as Illinois. Michigan calls charter schools \"Public School Academies (PSAs).\" Prop 22 (November 2022) repealed right-to-work for private-sector workers effective March 2023 / February 2024 (private sector NLRB workers); card-check (majority sign-up) available for MERC-jurisdiction schools under PERA.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB Region 7 (Detroit) applies to independently incorporated charter school nonprofits. MERC applies to locally/ISD-authorized charters (public employers). Many NAPCS MI schools are authorized by universities (CMU, GVSU, Bay Mills CC, Eastern Michigan, Oakland, Saginaw Valley, Lake Superior State, Macomb ISD, etc.) — authorizer analysis required for each school to determine jurisdiction. Arts Academy in the Woods (Macomb ISD-authorized) was organized via NLRB, suggesting NLRB asserts jurisdiction even for ISD-authorized schools in some cases.",
      "card_check": "Yes",
      "rtw": true,
      "dominant": "",
      "note": ""
    },
    "MN": {
      "lb_abbrev": "BMS (MN)",
      "lb_full": "Minnesota Bureau of Mediation Services",
      "lb_url": "https://mn.gov/bms/",
      "statute": "Minnesota Public Employment Labor Relations Act (PELRA), Minn. Stat. §179A. 2023 PELRA amendments explicitly included charter school employees as public employees — all MN charter organizing now routes through BMS. Pre-2023 certifications (TCGIS, CSE, Hiawatha) were processed via NLRB because schools were treated as private employers before the amendment.",
      "nlrb": "No",
      "nlrb_note": "NLRB processed historical certifications (TCGIS 2014, CSE 2014, Hiawatha 2021) before the 2023 PELRA amendment. Post-amendment, all MN charter labor matters route through BMS. Historical NLRB case numbers are preserved in individual reports for reference.",
      "card_check": "Yes",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "MO": {
      "lb_abbrev": "NLRB R14 (St. Louis) + NLRB R17 (Kansas City)",
      "lb_full": "National Labor Relations Board — Region 14 (St. Louis) and Region 17 (Kansas City). Missouri State Board of Mediation (SLBA) has limited jurisdiction and does not cover independently incorporated charters.",
      "lb_url": "https://www.nlrb.gov/search/case",
      "statute": "RSMo Chapter 160.400-160.425 (Missouri charter school law). RSMo 160.400.1: \"A charter school is an independent public school.\" RSMo 160.420: employment provisions (individual employee retention option only — no blanket district-CBA carryover). Mo. Const. Art. I 29: public-employee collective bargaining right (Independence-NEA v. Independence Sch. Dist., 2007). RSMo 105.510 excludes all teachers from the statutory public-sector labor act.",
      "nlrb": "Yes",
      "nlrb_note": "MO charters operated by nonprofit corporations are private employers under the NLRA. NLRB R14 (St. Louis) and R17 (Kansas City) are the operative boards. KIPP St. Louis High decertification (14-RD-341432) confirms NLRB jurisdiction. SLBA exception possible only for KCPS/SLPS-sponsored schools if employer-of-record is the district (verify).",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "NH": {
      "lb_abbrev": "PELRB (NH)",
      "lb_full": "New Hampshire Public Employee Labor Relations Board",
      "lb_url": "https://www.nh.gov/pelrb/",
      "statute": "RSA 273-A (Public Employee Labor Relations Act); RSA 194-B (Charter Schools Act). Charter school teachers who choose charter employment retain the right to join or organize separate bargaining units (RSA 194-B:14(II)(a)). Units must be separate from district units (RSA 194-B:14(II)(b)); prior district affiliation must be severed (RSA 194-B:14(II)(e)). CBAs must be filed with PELRB within 14 days of signing.",
      "nlrb": "No",
      "nlrb_note": "All NH charter school teachers are public employees under PELRB jurisdiction. NLRB does not apply to any NH charter school.",
      "card_check": "Yes",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "NJ": {
      "lb_abbrev": "PERC (NJ)",
      "lb_full": "Public Employment Relations Commission of New Jersey",
      "lb_url": "https://www.nj.gov/perc",
      "statute": "N.J.S.A. 18A:36A (NJ Charter School Law); N.J.S.A. 34:13A-1 et seq. All NJ charter schools are public schools; all employees are public employees.",
      "nlrb": "No",
      "nlrb_note": "NLRB does not apply to any NJ charter school. PERC (NJ) has full and exclusive jurisdiction.",
      "card_check": "Yes",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "NM": {
      "lb_abbrev": "PELRB (confirmed for J Paul Taylor Academy) / CONTESTED PELRB or NLRB Region 28 (other schools)",
      "lb_full": "J Paul Taylor Academy: PELRB jurisdiction confirmed (listed in PELRB All Known Bargaining Units, Feb 2026). Monte del Sol: NEA-NM CBA active (PELRB public employer framework or voluntary recognition). Remaining 3 schools: jurisdictional ambiguity unresolved — PELRB vs. NLRB Region 28.",
      "lb_url": "https://www.pelrb.nm.gov",
      "statute": "NM charter schools authorized by PEC, serve as independent LEAs. PEBA (NMSA 10-7E) covers state agencies/units of local government. Two NAPCS schools confirmed organized under NEA-NM via PELRB public employer framework, establishing that at least some NM charter schools are treated as public employers under PEBA. Jurisdictional question remains unsettled for the broader NM charter sector. Option C declared May 9, 2026 for unresolved schools.",
      "nlrb": "Yes",
      "nlrb_note": "",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "NY": {
      "lb_abbrev": "PERB(NY)",
      "lb_full": "New York Public Employment Relations Board",
      "lb_url": "https://perb.ny.gov",
      "statute": "NY Education Law Article 56 (Charter Schools Act); NY Civil Service Law Article 14 (Taylor Law). NY charter school employees are public employees. PERB(NY) has primary jurisdiction for certification and ULP proceedings.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB applies to independently incorporated NY charters that contest public employer status. Post-2016 NLRB jurisdictional expansion is real but partial — most certifications remain under PERB(NY). In practice: check PERB(NY) first, NLRB second.",
      "card_check": "Yes",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "OH": {
      "lb_abbrev": "NLRB (Region 8 / Region 9)",
      "lb_full": "National Labor Relations Board — Region 8 (Cleveland) and Region 9 (Cincinnati/Columbus)",
      "lb_url": "https://www.nlrb.gov",
      "statute": "National Labor Relations Act (NLRA). Ohio charter schools (\"community schools\" per ORC Chapter 3314) are classified as privately incorporated nonprofits — private employers under the NLRA. SERB (State Employment Relations Board, ORC Chapter 4117) does NOT apply. Settled by NLRB precedent: Menlo Park Academy (08-RC-286190, 2022), KIPP Columbus (09-CA-310589, 2022–2024), and a decade of prior Ohio charter elections all confirming NLRB jurisdiction.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB has exclusive jurisdiction over all 32 Ohio NAPCS charter schools. SERB jurisdiction has been argued and rejected in every Ohio charter labor case. The NLRB's ruling at Menlo Park Academy stated the school \"was not created directly by the state and is not a department or administrative arm of government.\" This is the operative standard for all Ohio community schools.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "OR": {
      "lb_abbrev": "ERB (OR)",
      "lb_full": "Oregon Employment Relations Board",
      "lb_url": "https://www.oregon.gov/erb",
      "statute": "PECBA — Public Employee Collective Bargaining Act (ORS 243.650 et seq.). All district-authorized OR charter schools are public employers under PECBA/ERB jurisdiction. ERB (not PERB — a common error) administers collective bargaining for Oregon public employers including charter schools authorized by local school districts. NLRB applies only to independently incorporated charter operators authorized by the State Board of Education (rare — Oregon Virtual Academy is the primary example in this dataset).",
      "nlrb": "Yes",
      "nlrb_note": "NLRB Region 19 (Seattle) applies to state-board-authorized independently incorporated charter operators — not to district-authorized dependent charters. Oregon Virtual Academy (ORVA, North Bend SD 13-authorized but independently incorporated) organized under NLRB 19-RC-278342 (cert Aug 2021). The Ivy School (state-board authorized) is under NLRB 19-RC-384252. All 34 NAPCS OR schools are district-authorized dependent charters — ERB jurisdiction only.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "PA": {
      "lb_abbrev": "NLRB",
      "lb_full": "National Labor Relations Board",
      "lb_url": "https://www.nlrb.gov",
      "statute": "National Labor Relations Act (NLRA). Pennsylvania Virtual Charter School, 364 NLRB No. 87 (2016) established that all PA charter schools incorporated as private nonprofits with self-perpetuating boards are private employers under NLRB jurisdiction — not public employers under PLRB/PERA. This landmark ruling covers all 23 NAPCS PA schools.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB Region 4 (Philadelphia) covers eastern PA schools; NLRB Region 6 (Pittsburgh) covers western PA schools; NLRB Region 5 (Baltimore) covers south-central PA (VIDA CS, Young Scholars of Central PA). All 23 NAPCS PA schools fall under NLRB jurisdiction per the 2016 landmark ruling.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "RI": {
      "lb_abbrev": "NLRB Region 1 (Boston)",
      "lb_full": "National Labor Relations Board, Region 1, Boston",
      "lb_url": "https://www.nlrb.gov/about-nlrb/who-we-are/regional-offices/region-1-boston",
      "statute": "Federal NLRA. All 42 RI charter schools are independently incorporated nonprofits — including the 3 LEA/District-authorized schools (Apprenticeship Exploration/Cranston; Times2 x2/Providence). RI charters are treated as private employers under the NLRA. The Rhode Island State Labor Relations Board (RISLRB, R.I.G.L. Ch. 28-7) has no jurisdiction over charter school employees. RI has no Right-to-Work law.",
      "nlrb": "Partial",
      "nlrb_note": "RISLRB does not apply. All charter types (Independent, Mayoral Academy, District) treated as private employers. Confirmed by both certified cases (Highlander, Paul Cuffee) filing exclusively in NLRB R1.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "VA": {
      "lb_abbrev": "Dual jurisdiction: Va. Code §40.1-57.2 (district CB law, 2 schools) / NLRB R5 Baltimore (5 schools)",
      "lb_full": "",
      "lb_url": "https://www.nlrb.gov/about-nlrb/who-we-are/regional-offices/region-5-baltimore",
      "statute": "",
      "nlrb": "Yes",
      "nlrb_note": "",
      "card_check": "No",
      "rtw": true,
      "dominant": "",
      "note": ""
    },
    "WA": {
      "lb_abbrev": "PERC (WA)",
      "lb_full": "Public Employment Relations Commission of Washington State",
      "lb_url": "https://perc.wa.gov",
      "statute": "RCW 41.56.0251 — applies RCW ch. 41.56 (PECBA) to all WA charter schools as public employers (enacted SB 6194, 2016). RCW 41.59.031 — charter schools are separate employers from any school district. Chapter 28A.710 RCW — Washington charter school law.",
      "nlrb": "No",
      "nlrb_note": "NLRB does not apply to any WA charter school. RCW 41.56.0251 and RCW 41.59.031 establish PERC (WA) as the exclusive labor board. Every WA charter school is a statutory public employer and a separate employer from any school district.",
      "card_check": "Yes",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "WI": {
      "lb_abbrev": "WERC (WI) / NLRB R18",
      "lb_full": "Wisconsin Employment Relations Commission (instrumentality); National Labor Relations Board Region 18 Minneapolis (non-instrumentality)",
      "lb_url": "https://werc.wi.gov",
      "statute": "Wis. Stat. §118.40(7) — school board must declare each LEA charter as instrumentality or non-instrumentality. Instrumentality (§118.40(7)(a)): board SHALL employ all personnel; employees retain WERC bargaining rights (§118.40(7)(ar)). Non-instrumentality (§118.40(7)(am)): board may NOT employ personnel; NLRB R18 jurisdiction. Non-LEA authorized charters (§118.40(2r)/(2x)): non-instrumentality by statute — NLRB R18. Act 10 (2011): WERC-jurisdiction units bargain base wages only, CPI-capped; annual recertification at 51% of all eligible voters. Act 10 ruled unconstitutional Dec 2, 2024 (Dane County); STAYED Jan 23, 2025 pending WI Court of Appeals (briefed Oct 2025). Act 10 does NOT apply to NLRB-jurisdiction employers.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB R18 (Minneapolis) applies to all non-instrumentality WI charters: (1) Non-LEA authorized schools (32 open schools — City of Milwaukee ×7, UW System ×9, UW-Milwaukee ×14, UW-Parkside ×1, Waukesha County ×1); (2) LEA-authorized non-instrumentality charters (~27+ schools including all 6 MPS non-instrumentality operators). Registry Authorizer_Type = LEA does NOT confirm instrumentality — individual school determination required.",
      "card_check": "No",
      "rtw": false,
      "dominant": "",
      "note": ""
    },
    "WV": {
      "lb_abbrev": "NLRB R9",
      "lb_full": "National Labor Relations Board — Region 9, Cincinnati, Ohio",
      "lb_url": "https://www.nlrb.gov/regional-office/region-9-cincinnati",
      "statute": "National Labor Relations Act (NLRA). WV charter schools are private NLRA employers under NLRB R9 jurisdiction. WV Code §18-5G-3(b)(7) requires charter schools to employ their own personnel. WV Code §18-5-45a explicitly declares that public employees in West Virginia have no statutory right to collective bargaining, mediation, or arbitration — but this applies to district employees, not charter school employees organized under NLRB.",
      "nlrb": "Yes",
      "nlrb_note": "NLRB R9 (Cincinnati) has exclusive jurisdiction over all WV charter schools. WV charters are private employers under NLRA per WV Code §18-5G-3(b)(7). No state public employee labor board has charter school jurisdiction in WV.",
      "card_check": "No",
      "rtw": true,
      "dominant": "",
      "note": ""
    }
  },
  "stateReports": {
    "AK": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/AK_State_Research_Report.pdf"
    },
    "AR": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/AR_State_Research_Report.pdf"
    },
    "AZ": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/AZ_State_Research_Report.pdf"
    },
    "CA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/CA_State_Research_Report.pdf"
    },
    "CO": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/CO_State_Research_Report.pdf"
    },
    "CT": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/CT_State_Research_Report.pdf"
    },
    "DC": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/DC_State_Research_Report.pdf"
    },
    "DE": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/DE_State_Research_Report.pdf"
    },
    "FL": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/FL_State_Research_Report.pdf"
    },
    "GA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/GA_State_Research_Report.pdf"
    },
    "HI": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/HI_State_Research_Report.pdf"
    },
    "IA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/IA_State_Research_Report.pdf"
    },
    "IL": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/IL_State_Research_Report.pdf"
    },
    "KS": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/KS_State_Research_Report.pdf"
    },
    "LA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/LA_State_Research_Report.pdf"
    },
    "MA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/MA_State_Research_Report.pdf"
    },
    "MD": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/MD_State_Research_Report.pdf"
    },
    "ME": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/ME_State_Research_Report.pdf"
    },
    "MI": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/MI_State_Research_Report.pdf"
    },
    "MN": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/MN_State_Research_Report.pdf"
    },
    "MO": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/MO_State_Research_Report.pdf"
    },
    "NH": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/NH_State_Research_Report.pdf"
    },
    "NJ": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/NJ_State_Research_Report.pdf"
    },
    "NM": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/NM_State_Research_Report.pdf"
    },
    "NY": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/NY_State_Research_Report.pdf"
    },
    "OH": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/OH_State_Research_Report.pdf"
    },
    "OR": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/OR_State_Research_Report.pdf"
    },
    "PA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/PA_State_Research_Report.pdf"
    },
    "RI": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/RI_State_Research_Report.pdf"
    },
    "VA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/VA_State_Research_Report.pdf"
    },
    "WA": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/WA_State_Research_Report.pdf"
    },
    "WI": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/WI_State_Research_Report.pdf"
    },
    "WV": {
      "netlifyUrl": "https://napcs-charter-school-census-dashboard.netlify.app/WV_State_Research_Report.pdf"
    }
  },
  "emoByState": {
    "AZ": {
      "permitted": "Yes",
      "statute": "ARS §15-183",
      "notes": "Unique: AZ allows for-profit entities as charter holders. All other states require nonprofit holders."
    },
    "CT": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. Sector is highly regulated and small (22 schools)."
    },
    "DC": {
      "permitted": "Yes",
      "statute": "(statute TBD)",
      "notes": "For-profit management permitted."
    },
    "DE": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. Small sector."
    },
    "FL": {
      "permitted": "Yes",
      "statute": "§1002.33",
      "notes": "For-profit management permitted."
    },
    "IL": {
      "permitted": "Yes",
      "statute": "(statute TBD)",
      "notes": "For-profit management permitted."
    },
    "LA": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. Significant EMO/CMO presence post-Katrina in New Orleans."
    },
    "MA": {
      "permitted": "Restricted",
      "statute": "603 CMR §1.02",
      "notes": "For-profit entities prohibited from holding charter. For-profit management contracts are a gray area — charter holder must be nonprofit."
    },
    "ME": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. Very small sector (12 schools)."
    },
    "MI": {
      "permitted": "Yes",
      "statute": "(statute TBD)",
      "notes": "MI explicitly permits for-profit management."
    },
    "MN": {
      "permitted": "Yes",
      "statute": "Minn. Stat. §124E.16",
      "notes": "For-profit management (EMO) is permitted but heavily regulated. §124E.16 requires detailed contract terms, conflict-of-interest prohibitions, and annual assurances. EMOs may not provide teachers (§124E.12 subd. 1, 2024 amendment) or loan funds to schools."
    },
    "NJ": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. PERC has full jurisdiction. Small-medium sector."
    },
    "NM": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. PELRB has no charter jurisdiction (NLRB applies). Connections Academy (for-profit) operates in state."
    },
    "NY": {
      "permitted": "Restricted",
      "statute": "Ed. Law §2851",
      "notes": "2010 law bars new charters from having for-profit managers. Six legacy charters (pre-2010) grandfathered."
    },
    "OH": {
      "permitted": "Yes",
      "statute": "ORC §3314",
      "notes": "Permitted. OH had significant for-profit EMO presence historically (White Hat Management)."
    },
    "OR": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. ERB has jurisdiction over district-authorized charters."
    },
    "PA": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. Edison Learning and other EMOs have historically operated in state. NLRB R4 exclusive jurisdiction."
    },
    "CA": {
      "permitted": "Yes",
      "statute": "Ed. Code §47620",
      "notes": "For-profit management permitted. Charter holder must be nonprofit."
    },
    "RI": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. Very small sector (42 schools)."
    },
    "HI": {
      "permitted": "No",
      "statute": "HRS §302D",
      "notes": "Not applicable: all HI charter school employees are state employees under HRS Ch. 89. No private management contracts exist — charters are state-sponsored with state employment. For-profit management is structurally excluded."
    },
    "WI": {
      "permitted": "Yes",
      "statute": "(statute TBD)",
      "notes": "For-profit management permitted."
    },
    "MD": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be a nonprofit or the LEA. In practice, all MD charters are district-authorized LEA schools — EMO contracts theoretically possible but no known examples."
    },
    "CO": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. SB23-111 (2023) expanded organizing rights but did not address EMO status."
    },
    "WA": {
      "permitted": "Yes",
      "statute": "RCW 28A.710",
      "notes": "No explicit EMO management prohibition. Charter holder must be nonprofit. PERC (WA) has full jurisdiction. Very small sector (18 schools)."
    },
    "GA": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit 501(c)(3). CSUSA and other for-profit managers have operated in state."
    },
    "MO": {
      "permitted": "Yes",
      "statute": "(no explicit statute)",
      "notes": "No state law explicitly prohibits for-profit management contracts. Charter holder must be nonprofit. KIPP St. Louis and other networks operate in state."
    }
  },
  "stateK12Enrollment": {
    "AK": 126000,
    "AL": 726000,
    "AR": 476000,
    "IA": 470000,
    "ID": 299000,
    "IN": 1018000,
    "KS": 468000,
    "MS": 437000,
    "NC": 1360000,
    "NH": 172000,
    "NV": 489000,
    "OK": 694000,
    "SC": 776000,
    "TN": 1013000,
    "UT": 680000,
    "TX": 5417000,
    "VA": 1252000,
    "WV": 250000,
    "WY": 91000,
    "AZ": 1132000,
    "CA": 5897000,
    "CO": 920000,
    "CT": 518000,
    "DC": 96000,
    "DE": 145000,
    "FL": 2973000,
    "GA": 1754000,
    "HI": 178000,
    "IL": 1870000,
    "LA": 682000,
    "MA": 985000,
    "MD": 912000,
    "ME": 177000,
    "MI": 1420000,
    "MN": 883000,
    "MO": 882000,
    "NJ": 1374000,
    "NM": 323000,
    "NY": 2552000,
    "OH": 1656000,
    "OR": 561000,
    "PA": 1693000,
    "RI": 141000,
    "WA": 1116000,
    "WI": 861000
  },
  "charterEnrollment": {
    "confirmedEnrollment": 241139,
    "dependentEnrollment": 183295,
    "combinedEnrollment": 424434,
    "organizingEnrollment": 9608,
    "totalTrackedEnrollment": 1244371,
    "enrollmentDensity": "34.1%",
    "schoolsWithEnrollment": 2486
  },
  "status_lists": {}
};

// NAPCS_REGISTRY_CONTENT — preserved from prior version
/**
 * NAPCS_REGISTRY_CONTENT
 * Drives the Registry tab panel in the dashboard.
 */
var NAPCS_REGISTRY_CONTENT = {
  "version": "v130",
  "lastUpdated": "June 16, 2026",
  "narrative": {
    "projectOverview": {
      "title": "Project Overview",
      "body": "The Charter School Registry is the foundational infrastructure for the NAPCS Unionization Research Project. It provides a complete, authoritative directory of charter schools across all research states — now at Registry v130, covering 7,888 verified open charter schools across 45 jurisdictions. The registry is enriched with authorizer data, labor board jurisdiction assignments, NCES ID crosswalk, geographic coordinates, school enrollment data from NCES CCD 2024–25, and union status findings from the research program. All jurisdictions with open charter schools are now included in the research universe."
    },
    "scope": {
      "title": "Scope",
      "body": "The Registry currently covers 24 states plus the District of Columbia, comprising 5,760 charter schools. Colorado and Washington are included in the registry but research sessions have not yet been conducted for those states. Coverage expands as new state research sessions are initiated — states are added to the registry before research begins, providing the school list that drives each state's labor board search protocol."
    },
    "methodology": {
      "title": "Methodology",
      "body": "The Registry is built on the NCES Common Core of Data (CCD) public school universe files for 2024–25 (released December 2025), filtered to charter schools. Each record is enriched through a multi-step process: authorizer identification and type classification, charter type determination (independent, CMO, dependent/instrumentality), labor board jurisdiction assignment, geographic coordinate verification, school enrollment data from the 2024–25 CCD universe, and website research conducted as part of the research program. Records are matched to NAPCS school IDs where applicable."
    },
    "dataSources": {
      "title": "Data Sources",
      "body": "Primary source: NCES CCD 2024–25 Public Elementary/Secondary School Universe Survey (released December 2025). This is the current vintage used for school enrollment figures (enrollment_2425 field) and school universe counts throughout the dashboard. Supplemental sources include state education agency charter school directories, authorizer websites, and geocoding services for coordinate verification. Union status is sourced exclusively from research staff primary research — labor board portal searches and school-level verification. CBA document links, where publicly available, are recorded in the registry and displayed in the school popup on the dashboard."
    },
    "challenges": {
      "title": "Key Data Challenges",
      "body": "Key data quality challenges include: schools that operate under a different legal entity than their common name, requiring name variant searches at labor boards; schools recently authorized that may not yet have NCES IDs assigned (flagged in the registry); the Carmen/Rocketship Wisconsin authorizer transition, where new NCES IDs are expected as schools are re-authorized under UWM; multi-campus CMO networks where labor cases are filed under the network employer name rather than individual campuses; and schools that have undergone authorizer transitions that change their jurisdiction type. A website gap-fill effort is currently underway for all completed research states. Where data gaps are identified, research staff may recommend targeted outreach to the relevant labor board or state education agency."
    },
    "architecture": {
      "title": "Dashboard Architecture",
      "body": "The Registry feeds the dashboard through seven regional JavaScript data files rebuilt from the master registry spreadsheet: napcs_schools_ca.js (California), napcs_schools_fl.js (Florida), napcs_schools_tx.js (Texas — placeholder for future research), napcs_schools_east.js, napcs_schools_midwest.js, napcs_schools_west.js, and napcs_schools_central.js. Each file covers a geographic cluster of states. Every school record includes an enrollment_2425 field sourced from the NCES CCD 2024–25 universe, enabling per-school enrollment display and state-level charter enrollment rollups. This regional architecture replaced the prior single napcs_schools.js file."
    }
  },
  "about": {
    "keyStats": [
      {
        "label": "Total census schools",
        "value": "7,888"
      },
      {
        "label": "Jurisdictions covered",
        "value": "45 jurisdictions (all charter states + DC, excl. KY)"
      },
      {
        "label": "Data currency date",
        "value": "June 16, 2026"
      },
      {
        "label": "Registry version",
        "value": "v130"
      },
      {
        "label": "Data vintage",
        "value": "NCES CCD 2024–25"
      },
      {
        "label": "Deferred jurisdictions",
        "value": "12 states deferred — PDR-018: AL, ID, IN, MS, NC, NV, OK, SC, TN, TX, UT, WY"
      }
    ]
  },
  "discovery": {
    "title": "Discovery Schools Program",
    "purpose": "The Discovery program documents charter schools outside the NAPCS research universe that are found to have organized staff during the course of registry sweeps and labor board research. These schools are tracked separately and require explicit approval before entering the dataset.",
    "approach": [
      "Schools identified during labor board sweeps that are not in the NAPCS school list are flagged as Discovery candidates.",
      "Each Discovery school is reviewed against the NAPCS universe criteria before approval.",
      "Approved Discovery schools receive a NAPCS-ADD ID assignment and are entered into the Environment Scan Findings tab — not the main dataset — pending sponsor review.",
      "Discovery schools confirmed organized through the approval gate are reported to the executive sponsor for a disposition decision."
    ],
    "keyStats": [
      {
        "label": "Discovery schools found (all states)",
        "value": "See state research reports"
      },
      {
        "label": "Approval gate",
        "value": "Sponsor sign-off required"
      },
      {
        "label": "ID scheme",
        "value": "NAPCS-ADD-[state]-[seq]"
      }
    ]
  }
};